unit inclist;

interface
  type
    tIncludelistEntry=record n :integer;name :string;model :string end;

  const
    includelist :array[0..949] of tIncludelistEntry=(
(n:1;	name:'xx_kabuto_flick';	model:'kb (0)'),
(n:1;	name:'xx_kabutolev1';		model:'kb (0..7)'),
(n:2;	name:'xx_mecc_flick';		model:'mc (0..7)'),
(n:2;	name:'xx_mecclev1';		model:'mc (0..7)'),
(n:3;	name:'xx_reaper_flick';		model:'rp (0..7)'),
(n:3;	name:'xx_reaperlev1';		model:'rp (0..7)'),
(n:4;	name:'xx_lander';		model:'m_lander (0)'),
(n:8;	name:'xx_vimp';			model:'vp (1..7)'),
(n:11;	name:'xx_smartie';		model:'sm (0..7)'),
(n:14;	name:'xx_mecc_flick';		model:'mc_bullet'),
(n:14;	name:'xx_mecclev1';		model:'mc_bullet'),
(n:14;	name:'xx_rpman_weapons';		model:'mc_bullet'),
(n:21;	name:'xx_mecc_flick';		model:'mc_gun (0..5)'),
(n:21;	name:'xx_mecclev1';		model:'mc_gun (0..5)'),
(n:21;	name:'xx_rpman_weapons';		model:'mc_gun (0..5)'),
(n:22;	name:'xx_mecc_flick';		model:'mc_shotgun (0..5)'),
(n:22;	name:'xx_mecclev1';		model:'mc_shotgun (0..5)'),
(n:22;	name:'xx_rpman_weapons';		model:'mc_shotgun (0..5)'),
(n:23;	name:'xx_mecclev1';		model:'mc_syringe'),
(n:23;	name:'xx_rpman_weapons';		model:'mc_syringe'),
(n:24;	name:'xx_reaper_spells';		model:'rw_tornado'),
(n:25;	name:'xx_mecclev1';		model:'mc_laser'),
(n:25;	name:'xx_rpman_weapons';		model:'mc_laser'),
(n:28;	name:'xx_mecc_flick';		model:'mc_beamring'),
(n:28;	name:'xx_mecclev1';		model:'mc_beamring'),
(n:28;	name:'xx_rpman_weapons';		model:'mc_beamring'),
(n:29;	name:'xx_mecclev1';		model:'mc_lasergun'),
(n:29;	name:'xx_rpman_weapons';		model:'mc_lasergun'),
(n:30;	name:'xx_raik';			model:'rp_bow (_..5)'),
(n:30;	name:'xx_reaper_flick';		model:'rp_bow (_..5)'),
(n:30;	name:'xx_reaperlev1';		model:'rp_bow (_..5)'),
(n:31;	name:'xx_efx';			model:'rp_glow'),
(n:33;	name:'xx_reaperlev1';		model:'rw_warning'),
(n:34;	name:'xx_reaperlev1';		model:'rparrow'),
(n:35;	name:'xx_reaperlev1';		model:'rp_fire'),
(n:36;	name:'xx_mecclev1';		model:'mcbush'),
(n:36;	name:'xx_rpman_weapons';		model:'mcbush'),
(n:37;	name:'xx_efx';			model:'rp_glow'),
(n:38;	name:'xx_mecc_flick';		model:'mc_zip'),
(n:38;	name:'xx_mecclev1';		model:'mc_zip'),
(n:38;	name:'xx_rpman_weapons';		model:'mc_zip'),
(n:40;	name:'xx_reaper_spells';		model:'mr_invisible'),
(n:42;	name:'xx_mecc_flick';		model:'mc_gun (0..5)'),
(n:42;	name:'xx_mecclev1';		model:'mc_gun (0..5)'),
(n:42;	name:'xx_rpman_weapons';		model:'mc_gun (0..5)'),
(n:43;	name:'xx_mecc_flick';		model:'mc_bullet'),
(n:43;	name:'xx_mecclev1';		model:'mc_bullet'),
(n:43;	name:'xx_rpman_weapons';		model:'mc_bullet'),
(n:44;	name:'xx_permanentaliens';		model:'ex_flash'),
(n:45;	name:'xx_permanentaliens';		model:'ex_smoke_ring'),
(n:49;	name:'xx_permanentaliens';		model:'mr_invisible (_,_)'),
(n:53;	name:'xx_smartie_stuff';		model:'pub (_..4)'),
(n:60;	name:'xx_mecclev1';		model:'mc_turret (_..4)'),
(n:60;	name:'xx_rpman_weapons';		model:'mc_turret (_..4)'),
(n:71;	name:'xx_efx';			model:'sm_glow'),
(n:73;	name:'xx_ripper';		model:'ripper (_,rip 1..6)'),
(n:74;	name:'xx_efx';			model:'smoke'),
(n:75;	name:'xx_seamonster';		model:'rm_seamonster (_..6)'),
(n:78;	name:'xx_rocks';			model:'rock_1'),
(n:79;	name:'xx_rocks';			model:'rock_2'),
(n:84;	name:'xx_mecc_flick';		model:'mcthrust'),
(n:84;	name:'xx_mecclev1';		model:'mcthrust'),
(n:84;	name:'xx_rpman_weapons';		model:'mcthrust'),
(n:85;	name:'xx_mecc_flick';		model:'mcthrust2'),
(n:85;	name:'xx_mecclev1';		model:'mcthrust2'),
(n:85;	name:'xx_rpman_weapons';		model:'mcthrust2'),
(n:90;	name:'xx_ripper';		model:'ripspit'),
(n:91;	name:'xx_rocks';			model:'rock_3'),
(n:92;	name:'xx_plants';		model:'b_pod (_..2)'),
(n:93;	name:'xx_plants';		model:'b_bush (_..1)'),
(n:101;	name:'xx_ptree';			model:'ptree'),
(n:102;	name:'xx_ptree';			model:'ptree_bob (_..7)'),
(n:109;	name:'xx_efx';			model:'dust'),
(n:118;	name:'xx_bridge';		model:'bridge'),
(n:121;	name:'xx_efx';			model:'water_rings'),
(n:121;	name:'xx_water_rings';		model:'water_rings'),
(n:123;	name:'xx_birds';			model:'flak (0..1)'),
(n:124;	name:'xx_birds';			model:'lobird (0)'),
(n:125;	name:'xx_ptree';			model:'b_leaf1'),
(n:127;	name:'xx_mecclev1';		model:'mcflag'),
(n:127;	name:'xx_rpman_weapons';		model:'mcflag'),
(n:128;	name:'xx_fish';			model:'shiner'),
(n:129;	name:'xx_plants';		model:'s_weeds'),
(n:130;	name:'xx_plants';		model:'b_lilly'),
(n:133;	name:'xx_mecclev1_nothrust';		model:'mc_nothrust (0)'),
(n:135;	name:'xx_efx';			model:'m_blueglow'),
(n:137;	name:'xx_efx';			model:'water_drip'),
(n:137;	name:'xx_water_rings';		model:'water_drip'),
(n:138;	name:'xx_plants';		model:'s_flower1'),
(n:208;	name:'xx_lander';		model:'mecc_crash1'),
(n:215;	name:'xx_reaperman';		model:'rpman (0..7)'),
(n:216;	name:'xx_smfemale';		model:'smf (0..6)'),
(n:218;	name:'xx_ripper';		model:'ripnest'),
(n:219;	name:'xx_ripper';		model:'mound'),
(n:220;	name:'xx_ripper';		model:'dirt1'),
(n:223;	name:'xx_birds';			model:'feather1'),
(n:224;	name:'xx_reaperman';		model:'rpm_horn (0..4)'),
(n:226;	name:'xx_ripper';		model:'ripnest_x'),
(n:229;	name:'xx_ripper';		model:'ripper (_,rip 1..6)'),
(n:230;	name:'xx_ripper';		model:'ripper (_,rip 1..6)'),
(n:232;	name:'xx_ripper';		model:'ripspitbig'),
(n:235;	name:'xx_smartie_stuff';		model:'sm_fork'),
(n:236;	name:'xx_smartie_stuff';		model:'sm_knife'),
(n:240;	name:'xx_reaperman';		model:'rpman_spear (_..4)'),
(n:245;	name:'xx_plants';		model:'mcbush'),
(n:247;	name:'xx_bridge';		model:'bridge_end'),
(n:254;	name:'xx_mecc_flick';		model:'mcjetpack'),
(n:254;	name:'xx_mecclev1';		model:'mcjetpack'),
(n:254;	name:'xx_rpman_weapons';		model:'mcjetpack'),
(n:256;	name:'xx_bridge';		model:'bridge_100ft'),
(n:257;	name:'xx_bridge';		model:'bridge_200ft'),
(n:258;	name:'xx_bridge';		model:'bridge_300ft'),
(n:270;	name:'xx_bigwalls';		model:'bw_arch_100'),
(n:271;	name:'xx_bigwalls';		model:'bw_arch_150'),
(n:272;	name:'xx_bigwalls';		model:'bw_arch_200'),
(n:273;	name:'xx_bigwalls';		model:'bw_corner'),
(n:274;	name:'xx_bigwalls';		model:'bw_wall_100'),
(n:275;	name:'xx_reaperman';		model:'rpman_tracer'),
(n:276;	name:'xx_offspring';		model:'rpman_grenade (_..1)'),
(n:276;	name:'xx_reaperman';		model:'rpman_grenade (_..1)'),
(n:276;	name:'xx_seamonster';		model:'rpman_grenade (_..1)'),
(n:300;	name:'xx_mecc_flick';		model:'mc_machinegun (0..5)'),
(n:300;	name:'xx_mecclev1';		model:'mc_machinegun (0..5)'),
(n:300;	name:'xx_rpman_weapons';		model:'mc_machinegun (0..5)'),
(n:301;	name:'xx_mecc_flick';		model:'mc_grenade (0,_)'),
(n:301;	name:'xx_mecclev1';		model:'mc_grenade (0,_)'),
(n:301;	name:'xx_rpman_weapons';		model:'mc_grenade (0,_)'),
(n:302;	name:'xx_mecclev1';		model:'mc_shotgun (0..5)'),
(n:302;	name:'xx_rpman_weapons';		model:'mc_shotgun (0..5)'),
(n:303;	name:'xx_mecclev1';		model:'mc_machinegun (0..5)'),
(n:303;	name:'xx_rpman_weapons';		model:'mc_machinegun (0..5)'),
(n:311;	name:'xx_reaper_flick';		model:'rp (3..7)'),
(n:311;	name:'xx_reaperlev1';		model:'rp (7)'),
(n:312;	name:'xx_reaperlev1';		model:'rp_sword_trail'),
(n:506;	name:'xx_smartie_stuff';		model:'sm_boat (0)'),
(n:507;	name:'xx_smartie_stuff';		model:'sm_cart (0)'),
(n:508;	name:'xx_smartie_stuff';		model:'sm_chimney (0)'),
(n:509;	name:'xx_smartie_stuff';		model:'sm_dome (0..4)'),
(n:510;	name:'xx_smartie_stuff';		model:'sm_domed1 (0)'),
(n:511;	name:'xx_smartie_stuff';		model:'sm_door (0..3)'),
(n:512;	name:'xx_smartie_stuff';		model:'sm_fences (0)'),
(n:513;	name:'xx_smartie_stuff';		model:'sm_seat (0)'),
(n:514;	name:'xx_smartie_stuff';		model:'sm_table (0)'),
(n:515;	name:'xx_smartie_stuff';		model:'sm_tower (0)'),
(n:516;	name:'xx_smartie_stuff';		model:'sm_well (0)'),
(n:517;	name:'xx_smartie_stuff';		model:'sm_window (0..2)'),
(n:518;	name:'xx_smartie_stuff';		model:'sm_tube (0..2)'),
(n:519;	name:'xx_smartie_stuff';		model:'sm_ladder (0)'),
(n:520;	name:'xx_smartie_stuff';		model:'sm_fences2 (0)'),
(n:521;	name:'xx_smartie_stuff';		model:'sm_post (0)'),
(n:522;	name:'xx_smartie_stuff';		model:'sm_hatch (0)'),
(n:523;	name:'xx_smartie_stuff';		model:'sm_vconnect1'),
(n:524;	name:'xx_smartie_stuff';		model:'sm_vconnect2'),
(n:525;	name:'xx_smartie_stuff';		model:'sm_sphere (_..2)'),
(n:527;	name:'xx_smartie_stuff';		model:'sm_sphere2'),
(n:528;	name:'xx_bridge';		model:'bridge_400ft'),
(n:529;	name:'xx_smartie_stuff';		model:'sm_spheredark (_..2)'),
(n:530;	name:'xx_smartie_stuff';		model:'sm_spheredark2'),
(n:531;	name:'xx_smartie_stuff';		model:'sm_post_tall'),
(n:532;	name:'xx_bridge';		model:'bridge_500ft'),
(n:533;	name:'xx_pier';			model:'pier_straight'),
(n:534;	name:'xx_pier';			model:'pier_bend90'),
(n:535;	name:'xx_pier';			model:'pier_round_rings'),
(n:536;	name:'xx_pier';			model:'pier_round_tile'),
(n:537;	name:'xx_pier';			model:'pier_square'),
(n:538;	name:'xx_pier';			model:'pier_post20'),
(n:539;	name:'xx_pier';			model:'pier_post30'),
(n:540;	name:'xx_pier';			model:'pier_post40'),
(n:541;	name:'xx_shadows';		model:'shadow_round'),
(n:542;	name:'xx_shadows';		model:'shadow_elipse'),
(n:543;	name:'xx_shadows';		model:'shadow_elipse2'),
(n:544;	name:'xx_smartie_stuff';		model:'smw_entrance'),
(n:545;	name:'xx_smartie_stuff';		model:'smw_curvehi'),
(n:546;	name:'xx_smartie_stuff';		model:'smw_column'),
(n:547;	name:'xx_smartie_stuff';		model:'smw_curvemed'),
(n:548;	name:'xx_smartie_stuff';		model:'smw_curvelow'),
(n:549;	name:'xx_smartie_stuff';		model:'smw_column2'),
(n:550;	name:'xx_smartie_stuff';		model:'smw_cwall_low'),
(n:551;	name:'xx_smartie_stuff';		model:'smw_wall_hi'),
(n:552;	name:'xx_smartie_stuff';		model:'smw_wall_med'),
(n:553;	name:'xx_smartie_stuff';		model:'smw_wall_hi_hole'),
(n:555;	name:'xx_bigwalls';		model:'bw_gate_portcullis'),
(n:556;	name:'xx_bigwalls';		model:'bw_wall_150'),
(n:557;	name:'xx_bigwalls';		model:'bw_wall_200'),
(n:558;	name:'xx_bigwalls';		model:'bw_parapit'),
(n:558;	name:'xx_bigwalls_lite';		model:'bw_parapit'),
(n:559;	name:'xx_bigwalls';		model:'bw_sr_arch_100'),
(n:560;	name:'xx_bigwalls';		model:'bw_sr_corner'),
(n:562;	name:'xx_verm';			model:'verm (0,2,4..7)'),
(n:563;	name:'xx_pier';			model:'canopy_1'),
(n:564;	name:'xx_pier';			model:'bent_post'),
(n:565;	name:'xx_pier';			model:'pier_straight_80'),
(n:566;	name:'xx_pier';			model:'pier_straight_160'),
(n:567;	name:'xx_bigwalls';		model:'bw_column_20'),
(n:567;	name:'xx_bigwalls_lite';		model:'bw_column_20'),
(n:568;	name:'xx_bigwalls';		model:'bw_column_30'),
(n:568;	name:'xx_bigwalls_lite';		model:'bw_column_30'),
(n:569;	name:'xx_bigwalls';		model:'bw_column_40'),
(n:569;	name:'xx_bigwalls_lite';		model:'bw_column_40'),
(n:570;	name:'xx_bigwalls';		model:'bw_column_60'),
(n:570;	name:'xx_bigwalls_lite';		model:'bw_column_60'),
(n:571;	name:'xx_verm';			model:'verm_egg (0)'),
(n:572;	name:'xx_verm';			model:'verm (0,2,4..7)'),
(n:574;	name:'xx_charger';		model:'charger (_..6)'),
(n:575;	name:'xx_sonak';			model:'sonak (0..6)'),
(n:576;	name:'xx_verm';			model:'verm_egg_d1 (0)'),
(n:577;	name:'xx_verm';			model:'verm_eggshell1'),
(n:578;	name:'xx_bigwalls';		model:'bw_bunker1'),
(n:579;	name:'xx_bigwalls';		model:'bw_top_platform'),
(n:580;	name:'xx_bigwalls';		model:'bw_top_connect1'),
(n:583;	name:'xx_smtimmy';		model:'smtimmy (0..6)'),
(n:583;	name:'xx_smtimmy_flick';		model:'smtimmy (0)'),
(n:584;	name:'xx_smborjoyzee';		model:'smborjoyzee (0..6)'),
(n:584;	name:'xx_smborjoyzee_flick';		model:'smborjoyzee (0,sm 7)'),
(n:586;	name:'xx_sonak';			model:'sonak_seat (0)'),
(n:587;	name:'xx_bigwalls';		model:'bw_wall_100_window'),
(n:588;	name:'xx_bigwalls';		model:'bw_bunker_low'),
(n:589;	name:'xx_smartie_stuff';		model:'smw_curvehi_m'),
(n:590;	name:'xx_smartie_stuff';		model:'smw_house1 (_..4)'),
(n:591;	name:'xx_smartie_stuff';		model:'smw_house2 (_..4)'),
(n:592;	name:'xx_smartie_stuff';		model:'smw_house3 (_..4)'),
(n:593;	name:'xx_smartie_stuff';		model:'smw_house4 (_..4)'),
(n:594;	name:'xx_smartie_stuff';		model:'smw_curvemed_m'),
(n:595;	name:'xx_smartie_stuff';		model:'smw_curvelow_m'),
(n:596;	name:'xx_smartie_stuff';		model:'sm_canopy_1_blue'),
(n:597;	name:'xx_smartie_stuff';		model:'sm_canopy_1_red'),
(n:598;	name:'xx_smartie_stuff';		model:'sm_canopy_1_green'),
(n:599;	name:'xx_smartie_stuff';		model:'sm_panel'),
(n:601;	name:'xx_bigwalls';		model:'bw_sr_arch_150'),
(n:602;	name:'xx_bigwalls';		model:'bw_sr_arch_200'),
(n:606;	name:'xx_smartie_stuff';		model:'sm_raft (0)'),
(n:607;	name:'xx_sonak';			model:'sonak_ring'),
(n:609;	name:'xx_ptree';			model:'ptree_simple'),
(n:610;	name:'xx_reaperman';		model:'rpman_tracer'),
(n:611;	name:'xx_bigwalls';		model:'bw_debri_piece1'),
(n:611;	name:'xx_bigwalls_lite';		model:'bw_debri_piece1'),
(n:612;	name:'xx_bigwalls';		model:'bw_debri_piece2'),
(n:612;	name:'xx_bigwalls_lite';		model:'bw_debri_piece2'),
(n:613;	name:'xx_bigwalls';		model:'bw_debri_piece3'),
(n:613;	name:'xx_bigwalls_lite';		model:'bw_debri_piece3'),
(n:614;	name:'xx_bigwalls';		model:'bw_debri_piece4'),
(n:614;	name:'xx_bigwalls_lite';		model:'bw_debri_piece4'),
(n:615;	name:'xx_bigwalls';		model:'bw_debri_column1'),
(n:615;	name:'xx_bigwalls_lite';		model:'bw_debri_column1'),
(n:616;	name:'xx_bigwalls';		model:'bw_debri_column2'),
(n:616;	name:'xx_bigwalls_lite';		model:'bw_debri_column2'),
(n:617;	name:'xx_bigwalls';		model:'bw_debri_bunker1'),
(n:617;	name:'xx_bigwalls_lite';		model:'bw_debri_bunker1'),
(n:618;	name:'xx_shadows';		model:'shadow_blastmark_1'),
(n:619;	name:'xx_shadows';		model:'shadow_blastmark_2'),
(n:620;	name:'xx_effects';		model:'dust_ring'),
(n:621;	name:'xx_effects';		model:'water_spray'),
(n:622;	name:'xx_effects';		model:'dust_blast'),
(n:623;	name:'xx_mecc_base';		model:'muzzle_flash'),
(n:623;	name:'xx_reaper_base';		model:'muzzle_flash'),
(n:623;	name:'xx_reaperman';		model:'muzzle_flash'),
(n:625;	name:'xx_reaperman';		model:'rpman_gunseat (0)'),
(n:627;	name:'xx_mecc_base';		model:'muzzle_flash2'),
(n:627;	name:'xx_reaper_base';		model:'muzzle_flash2'),
(n:627;	name:'xx_reaperman';		model:'muzzle_flash2'),
(n:628;	name:'xx_effects';		model:'dust_flash'),
(n:646;	name:'xx_effects';		model:'shrap_ground'),
(n:647;	name:'xx_mecclev1';		model:'mc_pickup_shells'),
(n:647;	name:'xx_rpman_weapons';		model:'mc_pickup_shells'),
(n:648;	name:'xx_mecclev1';		model:'mc_pickup_clips'),
(n:648;	name:'xx_rpman_weapons';		model:'mc_pickup_clips'),
(n:649;	name:'xx_mecclev1';		model:'mc_pickup_health'),
(n:649;	name:'xx_rpman_weapons';		model:'mc_pickup_health'),
(n:650;	name:'xx_mecclev1';		model:'mc_pickup_grenades'),
(n:650;	name:'xx_rpman_weapons';		model:'mc_pickup_grenades'),
(n:651;	name:'xx_mecclev1';		model:'mcbush'),
(n:651;	name:'xx_rpman_weapons';		model:'mcbush'),
(n:652;	name:'xx_bigwalls';		model:'bw_bunker1_d1'),
(n:652;	name:'xx_bigwalls_lite';		model:'bw_bunker1_d1'),
(n:653;	name:'xx_bigwalls';		model:'bw_bunker_top'),
(n:654;	name:'xx_bigwalls';		model:'bw_bunker_low_d1'),
(n:654;	name:'xx_bigwalls_lite';		model:'bw_bunker_low_d1'),
(n:655;	name:'xx_bigwalls';		model:'bw_column_20_d1'),
(n:655;	name:'xx_bigwalls_lite';		model:'bw_column_20_d1'),
(n:656;	name:'xx_bigwalls';		model:'bw_column_30_d1'),
(n:656;	name:'xx_bigwalls_lite';		model:'bw_column_30_d1'),
(n:657;	name:'xx_bigwalls';		model:'bw_column_40_d1'),
(n:657;	name:'xx_bigwalls_lite';		model:'bw_column_40_d1'),
(n:658;	name:'xx_bigwalls';		model:'bw_column_60_d1'),
(n:658;	name:'xx_bigwalls_lite';		model:'bw_column_60_d1'),
(n:659;	name:'xx_bigwalls';		model:'bw_parapit_d1'),
(n:659;	name:'xx_bigwalls_lite';		model:'bw_parapit_d1'),
(n:660;	name:'xx_mecc_flick';		model:'mc_machinegun_shell'),
(n:660;	name:'xx_mecclev1';		model:'mc_machinegun_shell'),
(n:660;	name:'xx_rpman_weapons';		model:'mc_machinegun_shell'),
(n:662;	name:'xx_guard_buildings';		model:'muzzle_flash'),
(n:662;	name:'xx_guard_turrets';		model:'muzzle_flash'),
(n:662;	name:'xx_mecc_base';		model:'muzzle_flash'),
(n:662;	name:'xx_mecc_flick';		model:'muzzle_flash'),
(n:662;	name:'xx_mecclev1';		model:'muzzle_flash'),
(n:662;	name:'xx_reaper_base';		model:'muzzle_flash'),
(n:662;	name:'xx_rpman_weapons';		model:'muzzle_flash'),
(n:663;	name:'xx_guard_buildings';		model:'muzzle_flash2'),
(n:663;	name:'xx_guard_turrets';		model:'muzzle_flash2'),
(n:663;	name:'xx_mecc_base';		model:'muzzle_flash2'),
(n:663;	name:'xx_mecc_flick';		model:'muzzle_flash2'),
(n:663;	name:'xx_mecclev1';		model:'muzzle_flash2'),
(n:663;	name:'xx_reaper_base';		model:'muzzle_flash2'),
(n:663;	name:'xx_rpman_weapons';		model:'muzzle_flash2'),
(n:664;	name:'xx_ptree';		model:'ptree_bob_d1'),
(n:665;	name:'xx_smborjoyzee';		model:'sm_staff'),
(n:665;	name:'xx_smborjoyzee_flick';		model:'sm_staff'),
(n:666;	name:'xx_rpqueen';		model:'rpqueen (0..7)'),
(n:666;	name:'xx_rpqueen_flick';		model:'rpqueen (0)'),
(n:667;	name:'xx_mecc_flick';		model:'blast_ring'),
(n:667;	name:'xx_mecclev1';		model:'blast_ring'),
(n:667;	name:'xx_rpman_weapons';		model:'blast_ring'),
(n:668;	name:'xx_mecc_flick';		model:'mc_shotgun_blast'),
(n:668;	name:'xx_mecclev1';		model:'mc_shotgun_blast'),
(n:668;	name:'xx_rpman_weapons';		model:'mc_shotgun_blast'),
(n:669;	name:'xx_raik';			model:'rp_sword (_..5)'),
(n:669;	name:'xx_reaper_flick';		model:'rp_sword (_..5)'),
(n:669;	name:'xx_reaperlev1';		model:'rp_sword (_..5)'),
(n:670;	name:'xx_smartie_stuff';		model:'sm_borj_house (0..6)'),
(n:671;	name:'xx_effects';		model:'dust_ball'),
(n:672;	name:'xx_effects';		model:'dust_smoke'),
(n:677;	name:'xx_kab_stuff';		model:'mud_ball'),
(n:678;	name:'xx_kab_stuff';		model:'hot_rock'),
(n:679;	name:'xx_markers';		model:'marker'),
(n:680;	name:'xx_rocks';			model:'rock_rpman_1'),
(n:681;	name:'xx_rocks';			model:'rock_rpman_2'),
(n:682;	name:'xx_kab_stuff';		model:'hot_rock_d'),
(n:683;	name:'xx_guard_log_launcher';		model:'log_carrier'),
(n:685;	name:'xx_permanentaliens';		model:'cleaner (0..2)'),
(n:686;	name:'xx_guard_barracks';		model:'barracks (_..5)'),
(n:687;	name:'xx_rocks';		model:'rock_rpman_3'),
(n:688;	name:'xx_guard_log_launcher';		model:'log_launcher'),
(n:689;	name:'xx_guard_log_launcher';		model:'log_launcher_base'),
(n:690;	name:'xx_birds';		model:'hitcher'),
(n:693;	name:'xx_reaperman';		model:'rpman_tuba (_..4)'),
(n:696;	name:'xx_effects';		model:'cast_spell'),
(n:697;	name:'xx_effects';		model:'rain'),
(n:702;	name:'xx_reaperlev1';		model:'rpbomb'),
(n:705;	name:'xx_bridge';		model:'bridge_200ft_d'),
(n:706;	name:'xx_bigwalls';		model:'bw_column_40_b'),
(n:706;	name:'xx_bigwalls_lite';		model:'bw_column_40_b'),
(n:707;	name:'xx_smartie_stuff';		model:'apple'),
(n:709;	name:'xx_mecc_base';		model:'wood_wall (_..3)'),
(n:710;	name:'xx_mecc_base';		model:'wood_gift (_..6)'),
(n:711;	name:'xx_mecc_base';		model:'wood_pub (_..6)'),
(n:712;	name:'xx_mecc_base';		model:'wood_shop (_..6)'),
(n:714;	name:'xx_mecc_base';		model:'stone_wall (_..4)'),
(n:716;	name:'xx_mecc_base';		model:'stone_gift (_..6)'),
(n:717;	name:'xx_mecc_base';		model:'stone_shop (_..6)'),
(n:729;	name:'xx_reaper_base';		model:'extractor_1 (_..6)'),
(n:730;	name:'xx_reaper_base';		model:'extractor_2 (_..6)'),
(n:735;	name:'xx_reaper_base';		model:'spellshop_1 (_..6)'),
(n:736;	name:'xx_reaper_base';		model:'spellshop_2 (_..6)'),
(n:742;	name:'xx_smyan';			model:'smyan (0..6)'),
(n:742;	name:'xx_smyan_flick';		model:'smyan (0)'),
(n:744;	name:'xx_mecc_base';		model:'wood_gate (_..4)'),
(n:745;	name:'xx_offspring';		model:'offspring (0..6)'),
(n:746;	name:'xx_offspring';		model:'offspring_egg (0)'),
(n:747;	name:'xx_offspring';		model:'offspring_egg_d1 (0)'),
(n:748;	name:'xx_offspring';		model:'offspring_eggshell1'),
(n:749;	name:'xx_kabutolev1';		model:'kb_hotspot'),
(n:750;	name:'xx_mecc_base';		model:'sm_firepit'),
(n:752;	name:'xx_smartie_stuff';		model:'sm_table_full'),
(n:753;	name:'xx_smartie_stuff';		model:'sm_shovel'),
(n:754;	name:'xx_smartie_stuff';		model:'sm_tankard'),
(n:755;	name:'xx_smartie_stuff';		model:'sm_hammer'),
(n:756;	name:'xx_smartie_stuff';		model:'sm_saw'),
(n:757;	name:'xx_smartie_stuff';		model:'sm_drumstick'),
(n:758;	name:'xx_smartie_stuff';		model:'sm_ribs'),
(n:759;	name:'xx_smartie_stuff';		model:'sm_pool'),
(n:761;	name:'xx_smartie_stuff';		model:'sm_planks'),
(n:762;	name:'xx_smartie_stuff';		model:'sm_woodshop_pile'),
(n:763;	name:'xx_mecc_base';		model:'d_wood_shop (_..4)'),
(n:764;	name:'xx_mecc_base';		model:'d_stone_gift (_..4)'),
(n:765;	name:'xx_mecc_base';		model:'d_stone_shop (_..4)'),
(n:768;	name:'xx_mecc_base';		model:'d_wood_gift (_..4)'),
(n:769;	name:'xx_mecc_base';		model:'d_wood_wall (_..2)'),
(n:771;	name:'xx_mecc_base';		model:'d_stone_wall (_..2)'),
(n:772;	name:'xx_mecc_base';		model:'d_wood_gate (_..2)'),
(n:773;	name:'xx_mecc_base';		model:'d_stone_gate (_..2)'),
(n:775;	name:'xx_mecc_base';		model:'stone_gate (_..4)'),
(n:779;	name:'xx_mecc_base';		model:'d_wood_pub (_..4)'),
(n:781;	name:'xx_mecclev1';		model:'mcthrust_nitro'),
(n:781;	name:'xx_rpman_weapons';		model:'mcthrust_nitro'),
(n:782;	name:'xx_smartie_stuff';		model:'sm_bricks'),
(n:783;	name:'xx_smartie_stuff';		model:'sm_metal'),
(n:785;	name:'xx_mecc_flick';		model:'mc_launcher (0..5)'),
(n:785;	name:'xx_mecclev1';		model:'mc_launcher (0..5)'),
(n:785;	name:'xx_rpman_weapons';		model:'mc_launcher (0..5)'),
(n:787;	name:'xx_mecc_flick';		model:'mc_snipergun (0..5)'),
(n:787;	name:'xx_mecclev1';		model:'mc_snipergun (0..5)'),
(n:787;	name:'xx_rpman_weapons';		model:'mc_snipergun (0..5)'),
(n:788;	name:'xx_sm_book';		model:'sm_book'),
(n:788;	name:'xx_smartie_stuff';		model:'sm_book'),
(n:788;	name:'xx_smyan_pagoda';		model:'sm_book'),
(n:790;	name:'xx_mecc_flick';		model:'mc_mortar (0..5)'),
(n:790;	name:'xx_mecclev1';		model:'mc_mortar (0..5)'),
(n:790;	name:'xx_rpman_weapons';		model:'mc_mortar (0..5)'),
(n:792;	name:'xx_mecclev1';		model:'mc_pickup_sn_clips'),
(n:792;	name:'xx_rpman_weapons';		model:'mc_pickup_sn_clips'),
(n:793;	name:'xx_mecclev1';		model:'mc_sniper_bullit'),
(n:793;	name:'xx_rpman_weapons';		model:'mc_sniper_bullit'),
(n:794;	name:'xx_efx';		model:'efx_flash'),
(n:796;	name:'xx_efx';		model:'efx_debri1'),
(n:797;	name:'xx_efx';		model:'efx_debri2'),
(n:798;	name:'xx_efx';		model:'efx_fireball'),
(n:799;	name:'xx_efx';		model:'efx_shockwave'),
(n:800;	name:'xx_mecc_flick';		model:'mc_rocket'),
(n:800;	name:'xx_mecclev1';		model:'mc_rocket'),
(n:800;	name:'xx_rpman_weapons';		model:'mc_rocket'),
(n:801;	name:'xx_mecclev1';		model:'mc_pickup_rockets'),
(n:801;	name:'xx_rpman_weapons';		model:'mc_pickup_rockets'),
(n:802;	name:'xx_mecclev1';		model:'mc_pickup_lbombs'),
(n:802;	name:'xx_rpman_weapons';		model:'mc_pickup_lbombs'),
(n:803;	name:'xx_mecc_flick';		model:'mc_rocket_proximity'),
(n:803;	name:'xx_mecclev1';		model:'mc_rocket_proximity'),
(n:803;	name:'xx_rpman_weapons';		model:'mc_rocket_proximity'),
(n:804;	name:'xx_mecclev1';		model:'mc_pickup_proximity'),
(n:804;	name:'xx_rpman_weapons';		model:'mc_pickup_proximity'),
(n:805;	name:'xx_mecc_flick';		model:'mc_mine'),
(n:805;	name:'xx_mecclev1';		model:'mc_mine (_..4)'),
(n:805;	name:'xx_rpman_weapons';		model:'mc_mine (_..4)'),
(n:806;	name:'xx_mecc_flick';		model:'mc_rocket_homing'),
(n:806;	name:'xx_mecclev1';		model:'mc_rocket_homing'),
(n:806;	name:'xx_rpman_weapons';		model:'mc_rocket_homing'),
(n:807;	name:'xx_mecclev1';		model:'mc_pickup_homing'),
(n:807;	name:'xx_rpman_weapons';		model:'mc_pickup_homing'),
(n:808;	name:'xx_mecc_flick';		model:'mc_lbomb'),
(n:808;	name:'xx_mecclev1';		model:'mc_lbomb'),
(n:808;	name:'xx_rpman_weapons';		model:'mc_lbomb'),
(n:809;	name:'xx_story4';		model:'s6_dungeon'),
(n:810;	name:'xx_story4';		model:'s6_cage'),
(n:811;	name:'xx_efx';			model:'efx_shockwave_w'),
(n:813;	name:'xx_efx';			model:'efx_dustball'),
(n:814;	name:'xx_efx';			model:'efx_smoke_black'),
(n:815;	name:'xx_efx';			model:'efx_fire_trail'),
(n:816;	name:'xx_efx';			model:'efx_shockwave_b'),
(n:817;	name:'xx_efx';			model:'efx_ref_horiz_circle'),
(n:818;	name:'xx_efx';			model:'efx_ref_sphere'),
(n:819;	name:'xx_efx';			model:'efx_ref_plume'),
(n:820;	name:'xx_efx';			model:'efx_bfire_trail'),
(n:821;	name:'xx_efx';			model:'efx_ref_line_back'),
(n:822;	name:'xx_mecc_flick';		model:'mc_popupbomb'),
(n:822;	name:'xx_mecclev1';		model:'mc_popupbomb'),
(n:822;	name:'xx_rpman_weapons';		model:'mc_popupbomb'),
(n:823;	name:'xx_efx';			model:'efx_ref_line_up'),
(n:824;	name:'xx_efx';			model:'efx_shockwave_bh'),
(n:826;	name:'xx_efx';			model:'efx_smoke_blue'),
(n:827;	name:'xx_efx';			model:'efx_gfire_trail'),
(n:828;	name:'xx_efx';			model:'efx_smoke_mgrey'),
(n:829;	name:'xx_efx';			model:'efx_sniper_flash'),
(n:830;	name:'xx_snow_stuff';		model:'snowtree'),
(n:830;	name:'xx_snowtree';		model:'snowtree'),
(n:834;	name:'xx_mecc_base';		model:'sm_dropoff'),
(n:834;	name:'xx_smartie_stuff';		model:'sm_dropoff'),
(n:835;	name:'xx_smartie_stuff';		model:'base_flag_red'),
(n:836;	name:'xx_smartie_stuff';		model:'base_flag_blue'),
(n:837;	name:'xx_efx';			model:'efx_ref_line_l2r'),
(n:839;	name:'xx_efx';			model:'efx_rain'),
(n:840;	name:'xx_efx';			model:'efx_snow'),
(n:841;	name:'xx_efx';			model:'efx_hail'),
(n:846;	name:'xx_efx';			model:'efx_waterdrop'),
(n:847;	name:'xx_efx';			model:'efx_glint'),
(n:848;	name:'xx_efx';			model:'efx_bubble_reflection'),
(n:849;	name:'xx_efx';			model:'efx_bubble_hilight'),
(n:850;	name:'xx_efx';			model:'efx_bubble_glow'),
(n:851;	name:'xx_reaper_base';		model:'rp_smartie_waiting'),
(n:854;	name:'xx_efx';			model:'efx_water_ring'),
(n:857;	name:'xx_reaper_base';		model:'sm_podium_reap'),
(n:858;	name:'xx_reaper_base';		model:'sm_dropoff_reap'),
(n:859;	name:'xx_efx';			model:'efx_vimp_ghost'),
(n:861;	name:'xx_efx';			model:'efx_water_bubble'),
(n:862;	name:'xx_efx';			model:'efx_ref_bubbles'),
(n:866;	name:'xx_efx';			model:'efx_blast_area_check'),
(n:867;	name:'xx_efx';			model:'efx_dust_ball'),
(n:868;	name:'xx_efx';			model:'efx_dust_swirl'),
(n:869;	name:'xx_efx';			model:'efx_mist'),
(n:872;	name:'xx_efx';			model:'efx_smartie_spell'),
(n:873;	name:'xx_efx';			model:'efx_ref_ground_hit'),
(n:874;	name:'xx_efx';			model:'efx_snow_ball'),
(n:875;	name:'xx_efx';			model:'efx_snow_swirl'),
(n:882;	name:'xx_reaper_base';		model:'rp_soul_dropoff'),
(n:883;	name:'xx_efx';			model:'efx_redlight'),
(n:884;	name:'xx_efx';			model:'mr_invisible'),
(n:885;	name:'xx_efx';			model:'efx_blue_wide'),
(n:886;	name:'xx_efx';			model:'efx_blue_wide'),
(n:887;	name:'xx_efx';			model:'efx_ref_spin'),
(n:888;	name:'xx_efx';			model:'efx_ref_firewall'),
(n:890;	name:'xx_efx';			model:'efx_fire'),
(n:892;	name:'xx_mecclev1';		model:'mc_jetpack_2'),
(n:892;	name:'xx_rpman_weapons';		model:'mc_jetpack_2'),
(n:894;	name:'xx_efx';			model:'efx_slow_spell'),
(n:897;	name:'xx_mecclev1';		model:'mc_repairpack'),
(n:897;	name:'xx_rpman_weapons';		model:'mc_repairpack'),
(n:898;	name:'xx_mecclev1';		model:'mc_repairgun'),
(n:898;	name:'xx_rpman_weapons';		model:'mc_repairgun'),
(n:899;	name:'xx_efx';			model:'efx_lightning'),
(n:900;	name:'xx_efx';			model:'efx_wood_debri_1'),
(n:901;	name:'xx_efx';			model:'efx_wood_debri_2'),
(n:902;	name:'xx_mecclev1';		model:'mc_shield'),
(n:902;	name:'xx_rpman_weapons';		model:'mc_shield'),
(n:903;	name:'xx_reaperlev1';		model:'rp_head'),
(n:904;	name:'xx_efx';			model:'efx_hail_missile'),
(n:905;	name:'xx_efx';			model:'efx_hail_shrapnel'),
(n:906;	name:'xx_efx';			model:'mc_chunk1'),
(n:907;	name:'xx_efx';			model:'mc_chunk2'),
(n:908;	name:'xx_efx';			model:'mc_chunk3'),
(n:909;	name:'xx_efx';			model:'mc_chunk4'),
(n:910;	name:'xx_efx';			model:'mc_chunk5'),
(n:911;	name:'xx_efx';			model:'mc_chunk6'),
(n:912;	name:'xx_efx';			model:'efx_metal_debri_1'),
(n:913;	name:'xx_efx';			model:'efx_stone_debri_1'),
(n:914;	name:'xx_efx';			model:'efx_splat'),
(n:915;	name:'xx_efx';			model:'efx_spray'),
(n:916;	name:'xx_efx';			model:'efx_blood'),
(n:917;	name:'xx_efx';			model:'efx_build_select'),
(n:918;	name:'xx_mecc_base';		model:'fun_house (_..6)'),
(n:919;	name:'xx_efx';			model:'efx_mc_death'),
(n:920;	name:'xx_mecclev1';		model:'mc_bushpack'),
(n:920;	name:'xx_rpman_weapons';		model:'mc_bushpack'),
(n:921;	name:'xx_efx';			model:'efx_circle_spell'),
(n:922;	name:'xx_efx';			model:'efx_debri_3'),
(n:923;	name:'xx_efx';			model:'efx_ref_circle_out'),
(n:924;	name:'xx_efx';			model:'efx_ref_sphere_in'),
(n:925;	name:'xx_efx';			model:'efx_rp_target'),
(n:926;	name:'xx_efx';			model:'efx_prx_sphere'),
(n:927;	name:'xx_efx';			model:'efx_fire_roll'),
(n:928;	name:'xx_reaperlev1';		model:'rp_bow_homing (_..5)'),
(n:929;	name:'xx_reaperlev1';		model:'rp_bow_sniper (_..5)'),
(n:930;	name:'xx_reaperlev1';		model:'rp_bow_rpg (_..5)'),
(n:931;	name:'xx_reaperlev1';		model:'rp_bow_powerup (_..5)'),
(n:932;	name:'xx_efx';			model:'efx_dark_fire'),
(n:933;	name:'xx_efx';			model:'efx_box_alpha'),
(n:934;	name:'xx_reaperlev1';		model:'rp_screamer'),
(n:935;	name:'xx_efx';			model:'efx_bglow'),
(n:936;	name:'xx_mecc_base';		model:'d_fun_house (_..4)'),
(n:937;	name:'xx_tools';			model:'scott_test'),
(n:938;	name:'xx_efx';			model:'efx_blooddrop'),
(n:942;	name:'xx_efx';			model:'efx_ice_target'),
(n:945;	name:'xx_offspring';		model:'offs_hotspot'),
(n:946;	name:'xx_efx';			model:'efx_swirl'),
(n:947;	name:'xx_efx';			model:'efx_lightning_1'),
(n:948;	name:'xx_efx';			model:'efx_lightning_2'),
(n:950;	name:'xx_efx';			model:'efx_rp_debri_1'),
(n:951;	name:'xx_smartie_stuff';		model:'sm_flag'),
(n:952;	name:'xx_smartie_stuff';		model:'sm_flag1'),
(n:953;	name:'xx_smartie_stuff';		model:'sm_flag2'),
(n:954;	name:'xx_smartie_stuff';		model:'sm_flag3'),
(n:955;	name:'xx_efx';			model:'efx_sun_yellow'),
(n:956;	name:'xx_efx';			model:'efx_sun_yellow_f'),
(n:959;	name:'xx_efx';			model:'efx_clockhand_1'),
(n:960;	name:'xx_efx';			model:'efx_clockhand_2'),
(n:964;	name:'xx_efx';			model:'efx_bow_charged'),
(n:965;	name:'xx_efx';			model:'efx_fire_ring'),
(n:966;	name:'xx_efx';			model:'efx_splash'),
(n:967;	name:'xx_reaper_base';		model:'d_spellshop_1 (_..4)'),
(n:968;	name:'xx_reaper_base';		model:'d_spellshop_2 (_..4)'),
(n:970;	name:'xx_reaper_base';		model:'d_extractor_2 (_..4)'),
(n:977;	name:'xx_bones';			model:'bone_femur'),
(n:978;	name:'xx_bones';			model:'bone_rib'),
(n:979;	name:'xx_bones';			model:'bone_spine'),
(n:980;	name:'xx_efx';			model:'efx_3dxhair'),
(n:981;	name:'xx_mecc_base';		model:'mecc_base_template_1'),
(n:983;	name:'xx_mecc_base';		model:'s_mecc_teleport (_..3)'),
(n:984;	name:'xx_mecc_base';		model:'s_mecc_gpad (_..4,4)'),
(n:985;	name:'xx_reaper_base';		model:'rp_base_template_1'),
(n:986;	name:'xx_mecc_base';		model:'s_mecc_shop (_..6)'),
(n:988;	name:'xx_mecc_base';		model:'s_mecc_tower (_..6)'),
(n:989;	name:'xx_reaper_base';		model:'s_reaper_shop (_..6)'),
(n:991;	name:'xx_mecc_base';		model:'gyro (0)'),
(n:992;	name:'xx_plants';		model:'shrub1 (_,1)'),
(n:993;	name:'xx_plants';		model:'shrub2'),
(n:994;	name:'xx_plants';		model:'shrub3'),
(n:996;	name:'xx_plants';		model:'shrub5 (_..3)'),
(n:997;	name:'xx_plants';		model:'shrub6 (_..3)'),
(n:998;	name:'xx_plants';		model:'shrub7 (_..3)'),
(n:999;	name:'xx_plants';		model:'shrub8 (_..3)'),
(n:1001;	name:'xx_story1';		model:'w_story1_hang'),
(n:1002;	name:'xx_smartie_stuff';		model:'smw_house5 (_..4)'),
(n:1003;	name:'xx_smartie_stuff';		model:'smw_house6 (_..4)'),
(n:1004;	name:'xx_tools';			model:'light'),
(n:1005;	name:'xx_permanentaliens';		model:'piranha'),
(n:1006;	name:'xx_ptree';			model:'ptree_bob_busted'),
(n:1007;	name:'xx_bigwalls';		model:'guard_center'),
(n:1007;	name:'xx_bigwalls_lite';		model:'guard_center'),
(n:1008;	name:'xx_story1';		model:'w_story1_ramp_1'),
(n:1009;	name:'xx_story1';		model:'w_story1_ramp_2 (_,_)'),
(n:1009;	name:'xx_story1';		model:'w_story1_ramp_2 (_,_)'),
(n:1009;	name:'xx_story1';		model:'w_story1_ramp_2 (_,_)'),
(n:1009;	name:'xx_story1';		model:'w_story1_ramp_2 (_,_)'),
(n:1010;	name:'xx_story1';		model:'w_story1_ramp_3'),
(n:1011;	name:'xx_story1';		model:'w_story1_ramp_4'),
(n:1012;	name:'xx_story1';		model:'w_story1_rock_1'),
(n:1013;	name:'xx_story1';		model:'w_story1_rock_2'),
(n:1014;	name:'xx_story1';		model:'w_story1_rock_3'),
(n:1015;	name:'xx_bigwalls';		model:'bw_gate_swing'),
(n:1016;	name:'xx_efx';			model:'efx_blur'),
(n:1017;	name:'xx_tools';			model:'sphere_coll'),
(n:1018;	name:'xx_kabutolev1';		model:'kabuto_shield'),
(n:1019;	name:'xx_menus';			model:'mu_mpselect'),
(n:1020;	name:'xx_menus';			model:'efx_menu'),
(n:1021;	name:'xx_guard_drawbridge';		model:'bw_drawbridge (_,bw_drawbridge_coll)'),
(n:1022;	name:'xx_bigwalls';		model:'bw_fence'),
(n:1023;	name:'xx_guard_prison';		model:'bw_prison (_..3)'),
(n:1024;	name:'xx_smartie_stuff';		model:'fun_house_int'),
(n:1025;	name:'xx_menus';			model:'mu_idselect'),
(n:1026;	name:'xx_menus';			model:'mu_wdselect'),
(n:1027;	name:'xx_menus';			model:'mu_gnselect'),
(n:1028;	name:'xx_smartie_stuff';		model:'mctower'),
(n:1029;	name:'xx_plants';		model:'shrub9 (_..3)'),
(n:1030;	name:'xx_plants';		model:'shrub10 (_..2)'),
(n:1031;	name:'xx_plants';		model:'shrub11'),
(n:1041;	name:'xx_smartie_stuff';		model:'mcbarrack (_..6)'),
(n:1042;	name:'xx_rocks';			model:'desert_rock_1'),
(n:1043;	name:'xx_rocks';			model:'desert_rock_2'),
(n:1044;	name:'xx_rocks';			model:'desert_rock_3'),
(n:1045;	name:'xx_ptree';			model:'ptree_canopy (_..2)'),
(n:1047;	name:'xx_reaperman';		model:'rpm_snipergun (_..4)'),
(n:1048;	name:'xx_reaperman';		model:'rpm_bazooka (_..4)'),
(n:1049;	name:'xx_reaperman';		model:'rpm_jetpack (_..4)'),
(n:1050;	name:'xx_guard_buildings';		model:'guard_tower1 (_..4)'),
(n:1051;	name:'xx_guard_buildings';		model:'guard_tower2 (_..4)'),
(n:1052;	name:'xx_markers';		model:'marker_spline'),
(n:1053;	name:'xx_story4';		model:'story4'),
(n:1054;	name:'xx_formations';		model:'1sonak_4guards'),
(n:1055;	name:'xx_reaperman';		model:'rpm_torch'),
(n:1056;	name:'xx_guard_drawbridge';		model:'bw_drawbridge_open (_,bw_drawbridgeo_coll)'),
(n:1057;	name:'xx_story4';		model:'story4_gate'),
(n:1058;	name:'xx_formations';		model:'1tsonak_4guards'),
(n:1059;	name:'xx_formations';		model:'1mcsonak_4guards'),
(n:1060;	name:'xx_guard_barracks';		model:'bw_minibarracks (_..4)'),
(n:1061;	name:'xx_guard_buildings';		model:'guard_sam (_..4)'),
(n:1061;	name:'xx_guard_turrets';		model:'guard_sam (_..4)'),
(n:1062;	name:'xx_guard_buildings';		model:'guard_turret (_..4)'),
(n:1062;	name:'xx_guard_turrets';		model:'guard_turret (_..4)'),
(n:1063;	name:'xx_guard_prison';		model:'bw_prisoncrater (_..3)'),
(n:1064;	name:'xx_charger';		model:'charger_hotspot'),
(n:1065;	name:'xx_guard_buildings';		model:'guard_lift (_..4)'),
(n:1066;	name:'xx_guard_buildings';		model:'guard_lift_strut (_..4)'),
(n:1067;	name:'xx_formations';		model:'2x4_guards'),
(n:1068;	name:'xx_formations';		model:'2x5_guards'),
(n:1069;	name:'xx_formations';		model:'2x3_guards'),
(n:1070;	name:'xx_formations';		model:'2x2_guards'),
(n:1071;	name:'xx_formations';		model:'2x1_guards'),
(n:1072;	name:'xx_guard_buildings';		model:'guard_bunker (_..4)'),
(n:1073;	name:'xx_smartie_stuff';		model:'sm_plate'),
(n:1074;	name:'xx_guard_buildings';		model:'guard_stable (_..4)'),
(n:1075;	name:'xx_smartie_stuff';		model:'potato'),
(n:1076;	name:'xx_jetski';		model:'rp_jetski'),
(n:1077;	name:'xx_guard_reaper_tower';		model:'bw_reapertower (_..5)'),
(n:1078;	name:'xx_smartie_stuff';		model:'potato_basket'),
(n:1079;	name:'xx_reaperman';		model:'rpm_telescope (_..4)'),
(n:1080;	name:'xx_raik';			model:'raik (0..7)'),
(n:1081;	name:'xx_snow_stuff';		model:'iceberg1'),
(n:1082;	name:'xx_smyan_pagoda';		model:'sm_pagoda (_..4)'),
(n:1083;	name:'xx_smyan_pagoda';		model:'sm_pagodagong (_..4)'),
(n:1084;	name:'xx_smartie_stuff';		model:'sm_pagodagate'),
(n:1084;	name:'xx_smyan_pagoda';		model:'sm_pagodagate'),
(n:1085;	name:'xx_snow_stuff';		model:'iceberg2'),
(n:1086;	name:'xx_snow_stuff';		model:'iceberg3'),
(n:1087;	name:'xx_snow_stuff';		model:'iceberg4'),
(n:1088;	name:'xx_snow_stuff';		model:'iceberg_ramp'),
(n:1089;	name:'xx_snow_stuff';		model:'ice_wall'),
(n:1092;	name:'xx_guard_buildings';		model:'guard_shop (_..4)'),
(n:1093;	name:'xx_mecc_base';		model:'stone_command (_..6)'),
(n:1094;	name:'xx_guard_buildings';		model:'guard_lift_base (_..4)'),
(n:1095;	name:'xx_mecc_base';		model:'wood_command'),
(n:1096;	name:'xx_rocks';			model:'story3_ridge'),
(n:1097;	name:'xx_guard_buildings';		model:'guard_buoy (_..4)'),
(n:1098;	name:'xx_markers';		model:'buoy_spline'),
(n:1099;	name:'xx_jetski';		model:'p_jetski_homing'),
(n:1100;	name:'xx_jetski';		model:'p_jetski_missile'),
(n:1101;	name:'xx_jetski';		model:'p_jetski_turbo'),
(n:1102;	name:'xx_efx';		model:'efx_sunflare'),
(n:1104;	name:'xx_ripper';		model:'rip_gore_head'),
(n:1105;	name:'xx_ripper';		model:'rip_gore_arm'),
(n:1106;	name:'xx_efx';		model:'efx_ref_machinegun'),
(n:1107;	name:'xx_efx';		model:'efx_sniper_flash2'),
(n:1108;	name:'xx_efx';		model:'efx_smoke_ring'),
(n:1109;	name:'xx_efx';		model:'efx_ref_vert_circle'),
(n:1111;	name:'xx_efx';		model:'efx_shotgun_blast'),
(n:1112;	name:'xx_efx';		model:'efx_ripper_lspit'),
(n:1113;	name:'xx_efx';		model:'efx_ripper_mspit'),
(n:1114;	name:'xx_mecc_flick';		model:'mc_shotgun_shell'),
(n:1114;	name:'xx_mecclev1';		model:'mc_shotgun_shell'),
(n:1114;	name:'xx_rpman_weapons';		model:'mc_shotgun_shell'),
(n:1115;	name:'xx_formations';		model:'1tsonak'),
(n:1116;	name:'xx_sonak';		model:'rpman_sonak_shell'),
(n:1117;	name:'xx_vimp';		model:'vimpfoodchunk1'),
(n:1118;	name:'xx_vimp';		model:'vimpfoodchunk2'),
(n:1119;	name:'xx_vimp';		model:'vimpfoodchunk3'),
(n:1120;	name:'xx_efx';		model:'efx_sam_debri'),
(n:1121;	name:'xx_efx';		model:'efx_ref_sam_explode'),
(n:1122;	name:'xx_efx';		model:'efx_ref_turret_explode'),
(n:1123;	name:'xx_mecclev1';		model:'mc_pickup_mines'),
(n:1123;	name:'xx_rpman_weapons';		model:'mc_pickup_mines'),
(n:1124;	name:'xx_efx';		model:'efx_turret_debri'),
(n:1125;	name:'xx_efx';		model:'efx_smoke_ring_white'),
(n:1126;	name:'xx_giants_logo_3d';		model:'giants_logo_3d'),
(n:1127;	name:'xx_guard_buildings';		model:'guard_tower1d (_..3)'),
(n:1128;	name:'xx_guard_buildings';		model:'guard_bunkerd (_..4)'),
(n:1129;	name:'xx_guard_buildings';		model:'guard_tower2d (_..3)'),
(n:1130;	name:'xx_efx';		model:'efx_sunflare2'),
(n:1134;	name:'xx_efx';		model:'efx_stable_debri_2'),
(n:1135;	name:'xx_efx';		model:'efx_stable_debri_1'),
(n:1136;	name:'xx_efx';		model:'efx_stable_debri_3'),
(n:1137;	name:'xx_efx';		model:'efx_stable_debri_4'),
(n:1138;	name:'xx_guard_buildings';		model:'guard_stabled'),
(n:1139;	name:'xx_efx';		model:'efx_sun_orange'),
(n:1140;	name:'xx_efx';		model:'efx_guard_tower2'),
(n:1142;	name:'xx_efx';		model:'efx_smoke_green'),
(n:1144;	name:'xx_ptree';		model:'ptree_bob_coll'),
(n:1145;	name:'xx_efx';		model:'efx_mc_lbomb'),
(n:1146;	name:'xx_rstory4';		model:'rstory4'),
(n:1147;	name:'xx_rstory3';		model:'r3_start_finish'),
(n:1147;	name:'xx_rstory5';		model:'r3_start_finish'),
(n:1148;	name:'xx_reaper_base';		model:'magic_wall1'),
(n:1149;	name:'xx_reaper_base';		model:'magic_wall2'),
(n:1150;	name:'xx_reaper_base';		model:'magic_gate1'),
(n:1151;	name:'xx_reaper_base';		model:'magic_gate2'),
(n:1152;	name:'xx_reaper_base';		model:'rp_workshop (_..6)'),
(n:1153;	name:'xx_reaper_base';		model:'d_rp_workshop (_..4)'),
(n:1154;	name:'xx_reaper_base';		model:'rp_generator (_..6)'),
(n:1155;	name:'xx_reaper_base';		model:'d_rp_generator (_..4)'),
(n:1156;	name:'xx_reaper_base';		model:'rp_fun_house (_..6)'),
(n:1157;	name:'xx_reaper_base';		model:'d_rp_fun_house (_..4)'),
(n:1158;	name:'xx_reaper_base';		model:'rp_command (_..6)'),
(n:1159;	name:'xx_jetski_rpm';		model:'rpm_jetski'),
(n:1160;	name:'xx_rstory3';		model:'r3_lap_marker'),
(n:1160;	name:'xx_rstory5';		model:'r3_lap_marker'),
(n:1161;	name:'xx_guard_army_barracks';		model:'guard_army_barracks (_..6)'),
(n:1162;	name:'xx_markers';		model:'army_spline'),
(n:1163;	name:'xx_rocks';		model:'pebble'),
(n:1164;	name:'xx_rstory3';		model:'r_grid (_..2)'),
(n:1164;	name:'xx_rstory5';		model:'r_grid'),
(n:1165;	name:'xx_efx';		model:'efx_rstory5_volcano'),
(n:1166;	name:'xx_rstory5';		model:'rstory5_cave'),
(n:1168;	name:'xx_toby';		model:'toby'),
(n:1169;	name:'xx_story4';		model:'story4_door'),
(n:1170;	name:'xx_efx';		model:'efx_ice_wall_debri'),
(n:1171;	name:'xx_reaper_ship';		model:'reaper_ship'),
(n:1172;	name:'xx_reaper_ship';		model:'reaper_ship_husk'),
(n:1173;	name:'xx_guard_army_barracks';		model:'guard_army_barracks_husk'),
(n:1174;	name:'xx_formations';		model:'7_flying_guards'),
(n:1175;	name:'xx_kab_stuff';		model:'mag_crystal'),
(n:1176;	name:'xx_formations';		model:'1_ripper'),
(n:1177;	name:'xx_formations';		model:'2_rippers'),
(n:1178;	name:'xx_formations';		model:'3_rippers'),
(n:1180;	name:'xx_formations';		model:'1_kamikazi'),
(n:1181;	name:'xx_reaper_base';		model:'s_reaper_pier (_..6)'),
(n:1185;	name:'xx_mecc_base';		model:'s_mecc_sam (_..6)'),
(n:1186;	name:'xx_mecc_base';		model:'s_mecc_turret (_..6)'),
(n:1187;	name:'xx_reaper_base';		model:'s_reaper_turret (_..6)'),
(n:1188;	name:'xx_reaper_base';		model:'s_reaper_sam (_..6)'),
(n:1189;	name:'xx_reaper_base';		model:'s_reaper_tower (_..6)'),
(n:1190;	name:'xx_guard_barracks';		model:'barracks_husk'),
(n:1192;	name:'xx_reaper_base';		model:'s_reaper_portal'),
(n:1198;	name:'xx_lander';		model:'mother_ship'),
(n:1199;	name:'xx_kab_stuff';		model:'mag_crystal_shard'),
(n:1200;	name:'xx_smyan';		model:'yan_sword'),
(n:1200;	name:'xx_smyan_flick';		model:'yan_sword'),
(n:1201;	name:'xx_story4';		model:'mc_cutout1'),
(n:1202;	name:'xx_story4';		model:'mc_cutout2'),
(n:1203;	name:'xx_reaperman';		model:'rpm_bomb (_..4)'),
(n:1204;	name:'xx_kab_stuff';		model:'kabuto_stone'),
(n:1204;	name:'xx_kabuto_flick';		model:'kabuto_stone'),
(n:1205;	name:'xx_efx';		model:'efx_portal'),
(n:1206;	name:'xx_efx';		model:'efx_mc_rocket'),
(n:1207;	name:'xx_giantwalls';		model:'giantwall1 (_..4)'),
(n:1208;	name:'xx_giantwalls';		model:'giantwall2 (_..4)'),
(n:1209;	name:'xx_giantwalls';		model:'giantwall3 (_..4)'),
(n:1210;	name:'xx_kab_stuff';		model:'kab_ash'),
(n:1211;	name:'xx_guard_buildings';		model:'guard_portal'),
(n:1212;	name:'xx_smtimmy';		model:'sm_timmygrave'),
(n:1212;	name:'xx_smtimmy_flick';		model:'sm_timmygrave'),
(n:1213;	name:'xx_guard_buildings';		model:'guard_portal_m'),
(n:1214;	name:'xx_reaper_ship';		model:'reaper_galleon'),
(n:1215;	name:'xx_kab_stuff';		model:'k_rock_gen'),
(n:1216;	name:'xx_kstory5';		model:'k_pocket'),
(n:1217;	name:'xx_smdoomed';		model:'smdoomed (0)'),
(n:1218;	name:'xx_smdoomed';		model:'smd_ground'),
(n:1219;	name:'xx_formations';		model:'5_flying_guards'),
(n:1220;	name:'xx_formations';		model:'3_flying_guards'),
(n:1221;	name:'xx_efx';		model:'efx_portal_charm'),
(n:1222;	name:'xx_reaperlev1';		model:'rp_mine  (_..4)'),
(n:1223;	name:'xx_reaperlev1';		model:'rp_pickup_mines'),
(n:1224;	name:'xx_reaperlev1';		model:'rp_health'),
(n:1225;	name:'xx_reaperlev1';		model:'rp_pickup_health'),
(n:1226;	name:'xx_guard_barracks';		model:'guard_ripperbarracks  (_..4)'),
(n:1228;	name:'xx_reaper_base';		model:'d_magic_wall1'),
(n:1229;	name:'xx_reaper_base';		model:'d_magic_wall2'),
(n:1230;	name:'xx_reaper_base';		model:'d_magic_gate1'),
(n:1231;	name:'xx_reaper_base';		model:'d_magic_gate2'),
(n:1233;	name:'xx_reaperlev1';		model:'rp_pickup_repair'),
(n:1234;	name:'xx_story1';		model:'w_story1_walls'),
(n:1235;	name:'xx_story1';		model:'w_story1_arch'),
(n:1236;	name:'xx_story1';		model:'w_story1_entrance'),
(n:1237;	name:'xx_mecc_base';		model:'d_stone_command  (_..4)'),
(n:1238;	name:'xx_reaper_base';		model:'d_rp_command  (_..4)'),
(n:1239;	name:'xx_raik';		model:'raik (7)'),
(n:1240;	name:'xx_rpqueen';		model:'rpqueen (7)'),
(n:1241;	name:'xx_theend';		model:'reg_kiss'),
(n:1242;	name:'xx_kab_stuff';		model:'k_lava_ball'),
(n:1242;	name:'xx_seamonster';		model:'k_lava_ball'),
(n:1243;	name:'xx_kab_stuff';		model:'k_volcano_debri'),
(n:1244;	name:'xx_kab_stuff';		model:'k_exhaust'),
(n:1245;	name:'xx_efx';		model:'efx_repair_ring'),
(n:1246;	name:'xx_kab_stuff';		model:'k_rock_gen_top'),
(n:1247;	name:'xx_story1';		model:'w_story1_mine'),
(n:1248;	name:'xx_story1';		model:'w_story1_walls_1'),
(n:1249;	name:'xx_story1';		model:'w_story1_walls_2'),
(n:1250;	name:'xx_story1';		model:'w_story1_walls_3'),
(n:1251;	name:'xx_story1';		model:'w_story1_walls_4'),
(n:1252;	name:'xx_story1';		model:'w_story1_walls_5'),
(n:1253;	name:'xx_story1';		model:'w_story1_walls_6'),
(n:1255;	name:'xx_reaper_base';		model:'efx_magic_w1'),
(n:1256;	name:'xx_efx';		model:'efx_portal_open_loop'),
(n:1257;	name:'xx_efx';		model:'efx_portal_open_flick'),
(n:1258;	name:'xx_efx';		model:'efx_portal_close_flick'),
(n:1259;	name:'xx_story1';		model:'w_story1_hang_flick'),
(n:1274;	name:'xx_plants';		model:'shrub5_coll'),
(n:1275;	name:'xx_tools';		model:'ripper_radius'),
(n:1276;	name:'xx_guard_barracks';		model:'barracks_story2 (_,barracks 1..5)'),
(n:1277;	name:'xx_giantwalls';		model:'giantwall4 (_..4)'),
(n:1279;	name:'xx_ambient';		model:'a_m1_near_beach'),
(n:1280;	name:'xx_ambient';		model:'a_m2_mnt_beach'),
(n:1281;	name:'xx_ambient';		model:'a_m3_cliffs_sand'),
(n:1282;	name:'xx_ambient';		model:'a_m4_beach_dark'),
(n:1283;	name:'xx_ambient';		model:'a_m5_beach_waves'),
(n:1284;	name:'xx_ambient';		model:'a_r1_light_rain'),
(n:1285;	name:'xx_ambient';		model:'a_r2_snow'),
(n:1286;	name:'xx_ambient';		model:'a_r3_race'),
(n:1287;	name:'xx_ambient';		model:'a_r4_darker'),
(n:1288;	name:'xx_ambient';		model:'a_r5_mountain'),
(n:1289;	name:'xx_ambient';		model:'a_k1'),
(n:1290;	name:'xx_ambient';		model:'a_k5_storm'),
(n:1291;	name:'xx_ambient';		model:'a_crashed_lander'),
(n:1293;	name:'xx_ambient';		model:'a_floating_gate'),
(n:1295;	name:'xx_ambient';		model:'a_cage'),
(n:1296;	name:'xx_ambient';		model:'a_distant_birds'),
(n:1297;	name:'xx_ambient';		model:'a_wind_gusts'),
(n:1298;	name:'xx_ambient';		model:'a_single_tree'),
(n:1299;	name:'xx_ambient';		model:'a_trees'),
(n:1300;	name:'xx_ambient';		model:'a_shoreline'),
(n:1301;	name:'xx_ambient';		model:'a_pools'),
(n:1302;	name:'xx_ambient';		model:'a_pier'),
(n:1303;	name:'xx_ambient';		model:'a_big_leaf_tree'),
(n:1304;	name:'xx_ambient';		model:'a_reaper_tower'),
(n:1305;	name:'xx_ambient';		model:'a_int_volcano'),
(n:1306;	name:'xx_ambient';		model:'a_smartie_village'),
(n:1308;	name:'xx_ambient';		model:'a_high_winds'),
(n:1309;	name:'xx_ambient';		model:'a_prison'),
(n:1310;	name:'xx_ambient';		model:'a_army_barracks'),
(n:1312;	name:'xx_ambient';		model:'a_forest_trees'),
(n:1313;	name:'xx_ambient';		model:'a_distant_animals'),
(n:1314;	name:'xx_formations';		model:'4_wide_guards'),
(n:1315;	name:'xx_ambient';		model:'a_shoreline_long'),
(n:1316;	name:'xx_ambient';		model:'a_shoreline_dark_short'),
(n:1317;	name:'xx_ambient';		model:'a_shoreline_dark_long'),
(n:1318;	name:'xx_ambient';		model:'a_river'),
(n:1319;	name:'xx_ambient';		model:'a_high_winds_light'),
(n:1320;	name:'xx_ambient';		model:'a_cold_wind_gusts'),
(n:1322;	name:'xx_efx';		model:'efx_giantwall4'),
(n:1323;	name:'xx_music_temp';		model:'a_kabuto_temp'),
(n:1324;	name:'xx_music_temp';		model:'a_mecc_temp'),
(n:1325;	name:'xx_music_temp';		model:'a_mecc_temp_amb'),
(n:1326;	name:'xx_music_temp';		model:'a_mecc_temp_battle'),
(n:1327;	name:'xx_music_temp';		model:'a_mecc_temp_sus'),
(n:1328;	name:'xx_story4';		model:'story4_tower (_..5)'),
(n:1330;	name:'xx_guard_buildings';		model:'guard_buoy_coll'),
(n:1331;	name:'xx_jetski_rpm';		model:'rpm_jetski_coll'),
(n:1332;	name:'xx_reaper_base';		model:'efx_magic_w2'),
(n:1333;	name:'xx_giantwalls';		model:'giantwall5 (_..4)'),
(n:1334;	name:'xx_kab_stuff';		model:'kabutopad'),
(n:1335;	name:'xx_smartie_stuff';		model:'smw_house7 (_..4)'),
(n:1336;	name:'xx_smartie_stuff';		model:'smw_house8 (_..4)'),
(n:1337;	name:'xx_sm_evil';		model:'sm_evil (0)'),
(n:1338;	name:'xx_ambient';		model:'a_k2'),
(n:1339;	name:'xx_ambient';		model:'a_k3'),
(n:1340;	name:'xx_ambient';		model:'a_k4'),
(n:1342;	name:'xx_ambient';		model:'a_special_tree'),
(n:1343;	name:'xx_ambient';		model:'a_pools_large'),
(n:1344;	name:'xx_ambient';		model:'a_boat'),
(n:1348;	name:'xx_smartie_stuff';		model:'sm_tower_timmy'),
(n:1349;	name:'xx_jetski';		model:'p_jetski_coll'),
(n:1350;	name:'xx_reaper_base';		model:'efx_magic_gate1'),
(n:1351;	name:'xx_reaper_base';		model:'efx_magic_gate2'),
(n:1354;	name:'xx_smartie_stuff';		model:'sm_table_dad'),
(n:1355;	name:'xx_ambient';		model:'a_volcano'),
(n:1356;	name:'xx_rstory5';		model:'rstory5_volcano_coll'),
(n:1357;	name:'xx_rstory5';		model:'rstory5_fake'),
(n:1358;	name:'xx_efx';		model:'efx_flare'),
(n:1359;	name:'xx_giantwalls';		model:'giantwall3_nick'),
(n:1360;	name:'xx_efx';		model:'efx_offspring_spit'),
(n:1361;	name:'xx_efx';		model:'efx_offspring_fire'),
(n:1363;	name:'xx_efx';		model:'efx_red_rings'),
(n:1364;	name:'xx_efx';		model:'efx_ref_crooked_line'),
(n:1365;	name:'xx_efx';		model:'efx_whizzer'),
(n:1366;	name:'xx_efx';		model:'efx_whizzer_sparkles'),
(n:1367;	name:'xx_efx';		model:'efx_deep_red'),
(n:1368;	name:'xx_efx';		model:'efx_whizzer_charml'),
(n:1369;	name:'xx_efx';		model:'efx_whizzer_charmr'),
(n:1370;	name:'xx_kstory5';		model:'k_spike'),
(n:1371;	name:'xx_kstory5';		model:'k_bridge_1'),
(n:1372;	name:'xx_kstory5';		model:'k_bridge_2'),
(n:1373;	name:'xx_kstory5';		model:'k_bridge_3'),
(n:1374;	name:'xx_jetski';		model:'sign'),
(n:1375;	name:'xx_kab_stuff';		model:'efx_crystal_debri'),
(n:1376;	name:'xx_guard_barracks';		model:'efx_ref_minibarracks'),
(n:1377;	name:'xx_guard_barracks';		model:'efx_mini_debri_top'),
(n:1378;	name:'xx_guard_barracks';		model:'efx_mini_debri_1'),
(n:1379;	name:'xx_guard_barracks';		model:'efx_mini_debri_2'),
(n:1380;	name:'xx_guard_barracks';		model:'efx_mini_debri_3'),
(n:1381;	name:'xx_guard_buildings';		model:'efx_ref_guard_tower_1'),
(n:1382;	name:'xx_guard_buildings';		model:'efx_guard_tower_debri_1'),
(n:1383;	name:'xx_guard_buildings';		model:'efx_guard_tower_debri_2'),
(n:1384;	name:'xx_guard_buildings';		model:'efx_guard_tower_debri_3'),
(n:1385;	name:'xx_guard_buildings';		model:'efx_guard_tower_debri_4'),
(n:1386;	name:'xx_guard_buildings';		model:'efx_guard_tower_debri_5'),
(n:1387;	name:'xx_guard_buildings';		model:'efx_ref_guard_tower_2'),
(n:1388;	name:'xx_guard_buildings';		model:'efx_tower_2_debri_1'),
(n:1389;	name:'xx_guard_buildings';		model:'efx_tower_2_debri_2'),
(n:1390;	name:'xx_guard_buildings';		model:'efx_tower_2_debri_3'),
(n:1391;	name:'xx_guard_barracks';		model:'efx_rpbarracks_debri_1'),
(n:1392;	name:'xx_guard_barracks';		model:'efx_rpbarracks_debri_2'),
(n:1393;	name:'xx_guard_barracks';		model:'efx_rpbarracks_debri_3'),
(n:1394;	name:'xx_giantwalls';		model:'efx_ref_giantwall3'),
(n:1395;	name:'xx_giantwalls';		model:'efx_giantwall_debri_1'),
(n:1396;	name:'xx_giantwalls';		model:'efx_giantwall_debri_2'),
(n:1397;	name:'xx_giantwalls';		model:'efx_giantwall_debri_3'),
(n:1398;	name:'xx_giantwalls';		model:'efx_giantwall_debri_4'),
(n:1399;	name:'xx_giantwalls';		model:'efx_giantwall_debri_5'),
(n:1400;	name:'xx_giantwalls';		model:'efx_giantwall_debri_6'),
(n:1401;	name:'xx_giantwalls';		model:'efx_giantwall_debri_7'),
(n:1402;	name:'xx_giantwalls';		model:'efx_giantwall_debri_8'),
(n:1403;	name:'xx_giantwalls';		model:'efx_giantwall_debri_9'),
(n:1404;	name:'xx_giantwalls';		model:'efx_giantwall_debri_10'),
(n:1405;	name:'xx_giantwalls';		model:'efx_giantwall_debri_11'),
(n:1406;	name:'xx_giantwalls';		model:'efx_giantwall_debri_12'),
(n:1407;	name:'xx_giantwalls';		model:'efx_giantwall_debri_13'),
(n:1408;	name:'xx_giantwalls';		model:'efx_giantwall_debri_14'),
(n:1409;	name:'xx_giantwalls';		model:'efx_ref_giantwall5'),
(n:1410;	name:'xx_giantwalls';		model:'efx_giantwall5_debri_1'),
(n:1411;	name:'xx_giantwalls';		model:'efx_giantwall3_debri_s'),
(n:1412;	name:'xx_efx';		model:'efx_smoke_ring_b'),
(n:1413;	name:'xx_bridge';		model:'bridge_wide'),
(n:1414;	name:'xx_guard_drawbridge';		model:'bw_drawbridge_coll'),
(n:1415;	name:'xx_guard_drawbridge';		model:'bw_drawbridgeo_coll'),
(n:1416;	name:'xx_kab_stuff';		model:'k_rock_gen_coll'),
(n:1417;	name:'xx_efx';		model:'efx_soot'));


{(n:1;name:'xx_kabuto_flick'),
(n:1;name:'xx_kabutolev1'),
(n:2;name:'xx_mecc_flick'),
(n:2;name:'xx_mecclev1'),
(n:3;name:'xx_reaper_flick'),
(n:3;name:'xx_reaperlev1'),
(n:4;name:'xx_lander'),
(n:8;name:'xx_vimp'),
(n:11;name:'xx_smartie'),
(n:14;name:'xx_mecc_flick'),
(n:14;name:'xx_mecclev1'),
(n:14;name:'xx_rpman_weapons'),
(n:21;name:'xx_mecc_flick'),
(n:21;name:'xx_mecclev1'),
(n:21;name:'xx_rpman_weapons'),
(n:22;name:'xx_mecc_flick'),
(n:22;name:'xx_mecclev1'),
(n:22;name:'xx_rpman_weapons'),
(n:23;name:'xx_mecclev1'),
(n:23;name:'xx_rpman_weapons'),
(n:24;name:'xx_reaper_spells'),
(n:25;name:'xx_mecclev1'),
(n:25;name:'xx_rpman_weapons'),
(n:28;name:'xx_mecc_flick'),
(n:28;name:'xx_mecclev1'),
(n:28;name:'xx_rpman_weapons'),
(n:29;name:'xx_mecclev1'),
(n:29;name:'xx_rpman_weapons'),
(n:30;name:'xx_raik'),
(n:30;name:'xx_reaper_flick'),
(n:30;name:'xx_reaperlev1'),
(n:31;name:'xx_efx'),
(n:33;name:'xx_reaperlev1'),
(n:34;name:'xx_reaperlev1'),
(n:35;name:'xx_reaperlev1'),
(n:36;name:'xx_mecclev1'),
(n:36;name:'xx_rpman_weapons'),
(n:37;name:'xx_efx'),
(n:38;name:'xx_mecc_flick'),
(n:38;name:'xx_mecclev1'),
(n:38;name:'xx_rpman_weapons'),
(n:40;name:'xx_reaper_spells'),
(n:42;name:'xx_mecc_flick'),
(n:42;name:'xx_mecclev1'),
(n:42;name:'xx_rpman_weapons'),
(n:43;name:'xx_mecc_flick'),
(n:43;name:'xx_mecclev1'),
(n:43;name:'xx_rpman_weapons'),
(n:44;name:'xx_permanentaliens'),
(n:45;name:'xx_permanentaliens'),
(n:49;name:'xx_permanentaliens'),
(n:53;name:'xx_smartie_stuff'),
(n:60;name:'xx_mecclev1'),
(n:60;name:'xx_rpman_weapons'),
(n:71;name:'xx_efx'),
(n:73;name:'xx_ripper'),
(n:74;name:'xx_efx'),
(n:75;name:'xx_seamonster'),
(n:78;name:'xx_rocks'),
(n:79;name:'xx_rocks'),
(n:84;name:'xx_mecc_flick'),
(n:84;name:'xx_mecclev1'),
(n:84;name:'xx_rpman_weapons'),
(n:85;name:'xx_mecc_flick'),
(n:85;name:'xx_mecclev1'),
(n:85;name:'xx_rpman_weapons'),
(n:90;name:'xx_ripper'),
(n:91;name:'xx_rocks'),
(n:92;name:'xx_plants'),
(n:93;name:'xx_plants'),
(n:101;name:'xx_ptree'),
(n:102;name:'xx_ptree'),
(n:109;name:'xx_efx'),
(n:118;name:'xx_bridge'),
(n:121;name:'xx_efx'),
(n:121;name:'xx_water_rings'),
(n:123;name:'xx_birds'),
(n:124;name:'xx_birds'),
(n:125;name:'xx_ptree'),
(n:127;name:'xx_mecclev1'),
(n:127;name:'xx_rpman_weapons'),
(n:128;name:'xx_fish'),
(n:129;name:'xx_plants'),
(n:130;name:'xx_plants'),
(n:133;name:'xx_mecclev1_nothrust'),
(n:135;name:'xx_efx'),
(n:137;name:'xx_efx'),
(n:137;name:'xx_water_rings'),
(n:138;name:'xx_plants'),
(n:208;name:'xx_lander'),
(n:215;name:'xx_reaperman'),
(n:216;name:'xx_smfemale'),
(n:218;name:'xx_ripper'),
(n:219;name:'xx_ripper'),
(n:220;name:'xx_ripper'),
(n:223;name:'xx_birds'),
(n:224;name:'xx_reaperman'),
(n:226;name:'xx_ripper'),
(n:229;name:'xx_ripper'),
(n:230;name:'xx_ripper'),
(n:232;name:'xx_ripper'),
(n:235;name:'xx_smartie_stuff'),
(n:236;name:'xx_smartie_stuff'),
(n:240;name:'xx_reaperman'),
(n:245;name:'xx_plants'),
(n:247;name:'xx_bridge'),
(n:254;name:'xx_mecc_flick'),
(n:254;name:'xx_mecclev1'),
(n:254;name:'xx_rpman_weapons'),
(n:256;name:'xx_bridge'),
(n:257;name:'xx_bridge'),
(n:258;name:'xx_bridge'),
(n:270;name:'xx_bigwalls'),
(n:271;name:'xx_bigwalls'),
(n:272;name:'xx_bigwalls'),
(n:273;name:'xx_bigwalls'),
(n:274;name:'xx_bigwalls'),
(n:275;name:'xx_reaperman'),
(n:276;name:'xx_offspring'),
(n:276;name:'xx_reaperman'),
(n:276;name:'xx_seamonster'),
(n:300;name:'xx_mecc_flick'),
(n:300;name:'xx_mecclev1'),
(n:300;name:'xx_rpman_weapons'),
(n:301;name:'xx_mecc_flick'),
(n:301;name:'xx_mecclev1'),
(n:301;name:'xx_rpman_weapons'),
(n:302;name:'xx_mecclev1'),
(n:302;name:'xx_rpman_weapons'),
(n:303;name:'xx_mecclev1'),
(n:303;name:'xx_rpman_weapons'),
(n:311;name:'xx_reaper_flick'),
(n:311;name:'xx_reaperlev1'),
(n:312;name:'xx_reaperlev1'),
(n:506;name:'xx_smartie_stuff'),
(n:507;name:'xx_smartie_stuff'),
(n:508;name:'xx_smartie_stuff'),
(n:509;name:'xx_smartie_stuff'),
(n:510;name:'xx_smartie_stuff'),
(n:511;name:'xx_smartie_stuff'),
(n:512;name:'xx_smartie_stuff'),
(n:513;name:'xx_smartie_stuff'),
(n:514;name:'xx_smartie_stuff'),
(n:515;name:'xx_smartie_stuff'),
(n:516;name:'xx_smartie_stuff'),
(n:517;name:'xx_smartie_stuff'),
(n:518;name:'xx_smartie_stuff'),
(n:519;name:'xx_smartie_stuff'),
(n:520;name:'xx_smartie_stuff'),
(n:521;name:'xx_smartie_stuff'),
(n:522;name:'xx_smartie_stuff'),
(n:523;name:'xx_smartie_stuff'),
(n:524;name:'xx_smartie_stuff'),
(n:525;name:'xx_smartie_stuff'),
(n:527;name:'xx_smartie_stuff'),
(n:528;name:'xx_bridge'),
(n:529;name:'xx_smartie_stuff'),
(n:530;name:'xx_smartie_stuff'),
(n:531;name:'xx_smartie_stuff'),
(n:532;name:'xx_bridge'),
(n:533;name:'xx_pier'),
(n:534;name:'xx_pier'),
(n:535;name:'xx_pier'),
(n:536;name:'xx_pier'),
(n:537;name:'xx_pier'),
(n:538;name:'xx_pier'),
(n:539;name:'xx_pier'),
(n:540;name:'xx_pier'),
(n:541;name:'xx_shadows'),
(n:542;name:'xx_shadows'),
(n:543;name:'xx_shadows'),
(n:544;name:'xx_smartie_stuff'),
(n:545;name:'xx_smartie_stuff'),
(n:546;name:'xx_smartie_stuff'),
(n:547;name:'xx_smartie_stuff'),
(n:548;name:'xx_smartie_stuff'),
(n:549;name:'xx_smartie_stuff'),
(n:550;name:'xx_smartie_stuff'),
(n:551;name:'xx_smartie_stuff'),
(n:552;name:'xx_smartie_stuff'),
(n:553;name:'xx_smartie_stuff'),
(n:555;name:'xx_bigwalls'),
(n:556;name:'xx_bigwalls'),
(n:557;name:'xx_bigwalls'),
(n:558;name:'xx_bigwalls'),
(n:558;name:'xx_bigwalls_lite'),
(n:559;name:'xx_bigwalls'),
(n:560;name:'xx_bigwalls'),
(n:562;name:'xx_verm'),
(n:563;name:'xx_pier'),
(n:564;name:'xx_pier'),
(n:565;name:'xx_pier'),
(n:566;name:'xx_pier'),
(n:567;name:'xx_bigwalls'),
(n:567;name:'xx_bigwalls_lite'),
(n:568;name:'xx_bigwalls'),
(n:568;name:'xx_bigwalls_lite'),
(n:569;name:'xx_bigwalls'),
(n:569;name:'xx_bigwalls_lite'),
(n:570;name:'xx_bigwalls'),
(n:570;name:'xx_bigwalls_lite'),
(n:571;name:'xx_verm'),
(n:572;name:'xx_verm'),
(n:574;name:'xx_charger'),
(n:575;name:'xx_sonak'),
(n:576;name:'xx_verm'),
(n:577;name:'xx_verm'),
(n:578;name:'xx_bigwalls'),
(n:579;name:'xx_bigwalls'),
(n:580;name:'xx_bigwalls'),
(n:583;name:'xx_smtimmy'),
(n:583;name:'xx_smtimmy_flick'),
(n:584;name:'xx_smborjoyzee'),
(n:584;name:'xx_smborjoyzee_flick'),
(n:586;name:'xx_sonak'),
(n:587;name:'xx_bigwalls'),
(n:588;name:'xx_bigwalls'),
(n:589;name:'xx_smartie_stuff'),
(n:590;name:'xx_smartie_stuff'),
(n:591;name:'xx_smartie_stuff'),
(n:592;name:'xx_smartie_stuff'),
(n:593;name:'xx_smartie_stuff'),
(n:594;name:'xx_smartie_stuff'),
(n:595;name:'xx_smartie_stuff'),
(n:596;name:'xx_smartie_stuff'),
(n:597;name:'xx_smartie_stuff'),
(n:598;name:'xx_smartie_stuff'),
(n:599;name:'xx_smartie_stuff'),
(n:601;name:'xx_bigwalls'),
(n:602;name:'xx_bigwalls'),
(n:606;name:'xx_smartie_stuff'),
(n:607;name:'xx_sonak'),
(n:609;name:'xx_ptree'),
(n:610;name:'xx_reaperman'),
(n:611;name:'xx_bigwalls'),
(n:611;name:'xx_bigwalls_lite'),
(n:612;name:'xx_bigwalls'),
(n:612;name:'xx_bigwalls_lite'),
(n:613;name:'xx_bigwalls'),
(n:613;name:'xx_bigwalls_lite'),
(n:614;name:'xx_bigwalls'),
(n:614;name:'xx_bigwalls_lite'),
(n:615;name:'xx_bigwalls'),
(n:615;name:'xx_bigwalls_lite'),
(n:616;name:'xx_bigwalls'),
(n:616;name:'xx_bigwalls_lite'),
(n:617;name:'xx_bigwalls'),
(n:617;name:'xx_bigwalls_lite'),
(n:618;name:'xx_shadows'),
(n:619;name:'xx_shadows'),
(n:620;name:'xx_effects'),
(n:621;name:'xx_effects'),
(n:622;name:'xx_effects'),
(n:623;name:'xx_mecc_base'),
(n:623;name:'xx_reaper_base'),
(n:623;name:'xx_reaperman'),
(n:625;name:'xx_reaperman'),
(n:627;name:'xx_mecc_base'),
(n:627;name:'xx_reaper_base'),
(n:627;name:'xx_reaperman'),
(n:628;name:'xx_effects'),
(n:646;name:'xx_effects'),
(n:647;name:'xx_mecclev1'),
(n:647;name:'xx_rpman_weapons'),
(n:648;name:'xx_mecclev1'),
(n:648;name:'xx_rpman_weapons'),
(n:649;name:'xx_mecclev1'),
(n:649;name:'xx_rpman_weapons'),
(n:650;name:'xx_mecclev1'),
(n:650;name:'xx_rpman_weapons'),
(n:651;name:'xx_mecclev1'),
(n:651;name:'xx_rpman_weapons'),
(n:652;name:'xx_bigwalls'),
(n:652;name:'xx_bigwalls_lite'),
(n:653;name:'xx_bigwalls'),
(n:654;name:'xx_bigwalls'),
(n:654;name:'xx_bigwalls_lite'),
(n:655;name:'xx_bigwalls'),
(n:655;name:'xx_bigwalls_lite'),
(n:656;name:'xx_bigwalls'),
(n:656;name:'xx_bigwalls_lite'),
(n:657;name:'xx_bigwalls'),
(n:657;name:'xx_bigwalls_lite'),
(n:658;name:'xx_bigwalls'),
(n:658;name:'xx_bigwalls_lite'),
(n:659;name:'xx_bigwalls'),
(n:659;name:'xx_bigwalls_lite'),
(n:660;name:'xx_mecc_flick'),
(n:660;name:'xx_mecclev1'),
(n:660;name:'xx_rpman_weapons'),
(n:662;name:'xx_guard_buildings'),
(n:662;name:'xx_guard_turrets'),
(n:662;name:'xx_mecc_base'),
(n:662;name:'xx_mecc_flick'),
(n:662;name:'xx_mecclev1'),
(n:662;name:'xx_reaper_base'),
(n:662;name:'xx_rpman_weapons'),
(n:663;name:'xx_guard_buildings'),
(n:663;name:'xx_guard_turrets'),
(n:663;name:'xx_mecc_base'),
(n:663;name:'xx_mecc_flick'),
(n:663;name:'xx_mecclev1'),
(n:663;name:'xx_reaper_base'),
(n:663;name:'xx_rpman_weapons'),
(n:664;name:'xx_ptree'),
(n:665;name:'xx_smborjoyzee'),
(n:665;name:'xx_smborjoyzee_flick'),
(n:666;name:'xx_rpqueen'),
(n:666;name:'xx_rpqueen_flick'),
(n:667;name:'xx_mecc_flick'),
(n:667;name:'xx_mecclev1'),
(n:667;name:'xx_rpman_weapons'),
(n:668;name:'xx_mecc_flick'),
(n:668;name:'xx_mecclev1'),
(n:668;name:'xx_rpman_weapons'),
(n:669;name:'xx_raik'),
(n:669;name:'xx_reaper_flick'),
(n:669;name:'xx_reaperlev1'),
(n:670;name:'xx_smartie_stuff'),
(n:671;name:'xx_effects'),
(n:672;name:'xx_effects'),
(n:677;name:'xx_kab_stuff'),
(n:678;name:'xx_kab_stuff'),
(n:679;name:'xx_markers'),
(n:680;name:'xx_rocks'),
(n:681;name:'xx_rocks'),
(n:682;name:'xx_kab_stuff'),
(n:683;name:'xx_guard_log_launcher'),
(n:685;name:'xx_permanentaliens'),
(n:686;name:'xx_guard_barracks'),
(n:687;name:'xx_rocks'),
(n:688;name:'xx_guard_log_launcher'),
(n:689;name:'xx_guard_log_launcher'),
(n:690;name:'xx_birds'),
(n:693;name:'xx_reaperman'),
(n:696;name:'xx_effects'),
(n:697;name:'xx_effects'),
(n:702;name:'xx_reaperlev1'),
(n:705;name:'xx_bridge'),
(n:706;name:'xx_bigwalls'),
(n:706;name:'xx_bigwalls_lite'),
(n:707;name:'xx_smartie_stuff'),
(n:709;name:'xx_mecc_base'),
(n:710;name:'xx_mecc_base'),
(n:711;name:'xx_mecc_base'),
(n:712;name:'xx_mecc_base'),
(n:714;name:'xx_mecc_base'),
(n:716;name:'xx_mecc_base'),
(n:717;name:'xx_mecc_base'),
(n:729;name:'xx_reaper_base'),
(n:730;name:'xx_reaper_base'),
(n:735;name:'xx_reaper_base'),
(n:736;name:'xx_reaper_base'),
(n:742;name:'xx_smyan'),
(n:742;name:'xx_smyan_flick'),
(n:744;name:'xx_mecc_base'),
(n:745;name:'xx_offspring'),
(n:746;name:'xx_offspring'),
(n:747;name:'xx_offspring'),
(n:748;name:'xx_offspring'),
(n:749;name:'xx_kabutolev1'),
(n:750;name:'xx_mecc_base'),
(n:752;name:'xx_smartie_stuff'),
(n:753;name:'xx_smartie_stuff'),
(n:754;name:'xx_smartie_stuff'),
(n:755;name:'xx_smartie_stuff'),
(n:756;name:'xx_smartie_stuff'),
(n:757;name:'xx_smartie_stuff'),
(n:758;name:'xx_smartie_stuff'),
(n:759;name:'xx_smartie_stuff'),
(n:761;name:'xx_smartie_stuff'),
(n:762;name:'xx_smartie_stuff'),
(n:763;name:'xx_mecc_base'),
(n:764;name:'xx_mecc_base'),
(n:765;name:'xx_mecc_base'),
(n:768;name:'xx_mecc_base'),
(n:769;name:'xx_mecc_base'),
(n:771;name:'xx_mecc_base'),
(n:772;name:'xx_mecc_base'),
(n:773;name:'xx_mecc_base'),
(n:775;name:'xx_mecc_base'),
(n:779;name:'xx_mecc_base'),
(n:781;name:'xx_mecclev1'),
(n:781;name:'xx_rpman_weapons'),
(n:782;name:'xx_smartie_stuff'),
(n:783;name:'xx_smartie_stuff'),
(n:785;name:'xx_mecc_flick'),
(n:785;name:'xx_mecclev1'),
(n:785;name:'xx_rpman_weapons'),
(n:787;name:'xx_mecc_flick'),
(n:787;name:'xx_mecclev1'),
(n:787;name:'xx_rpman_weapons'),
(n:788;name:'xx_sm_book'),
(n:788;name:'xx_smartie_stuff'),
(n:788;name:'xx_smyan_pagoda'),
(n:790;name:'xx_mecc_flick'),
(n:790;name:'xx_mecclev1'),
(n:790;name:'xx_rpman_weapons'),
(n:792;name:'xx_mecclev1'),
(n:792;name:'xx_rpman_weapons'),
(n:793;name:'xx_mecclev1'),
(n:793;name:'xx_rpman_weapons'),
(n:794;name:'xx_efx'),
(n:796;name:'xx_efx'),
(n:797;name:'xx_efx'),
(n:798;name:'xx_efx'),
(n:799;name:'xx_efx'),
(n:800;name:'xx_mecc_flick'),
(n:800;name:'xx_mecclev1'),
(n:800;name:'xx_rpman_weapons'),
(n:801;name:'xx_mecclev1'),
(n:801;name:'xx_rpman_weapons'),
(n:802;name:'xx_mecclev1'),
(n:802;name:'xx_rpman_weapons'),
(n:803;name:'xx_mecc_flick'),
(n:803;name:'xx_mecclev1'),
(n:803;name:'xx_rpman_weapons'),
(n:804;name:'xx_mecclev1'),
(n:804;name:'xx_rpman_weapons'),
(n:805;name:'xx_mecc_flick'),
(n:805;name:'xx_mecclev1'),
(n:805;name:'xx_rpman_weapons'),
(n:806;name:'xx_mecc_flick'),
(n:806;name:'xx_mecclev1'),
(n:806;name:'xx_rpman_weapons'),
(n:807;name:'xx_mecclev1'),
(n:807;name:'xx_rpman_weapons'),
(n:808;name:'xx_mecc_flick'),
(n:808;name:'xx_mecclev1'),
(n:808;name:'xx_rpman_weapons'),
(n:809;name:'xx_story4'),
(n:810;name:'xx_story4'),
(n:811;name:'xx_efx'),
(n:813;name:'xx_efx'),
(n:814;name:'xx_efx'),
(n:815;name:'xx_efx'),
(n:816;name:'xx_efx'),
(n:817;name:'xx_efx'),
(n:818;name:'xx_efx'),
(n:819;name:'xx_efx'),
(n:820;name:'xx_efx'),
(n:821;name:'xx_efx'),
(n:822;name:'xx_mecc_flick'),
(n:822;name:'xx_mecclev1'),
(n:822;name:'xx_rpman_weapons'),
(n:823;name:'xx_efx'),
(n:824;name:'xx_efx'),
(n:826;name:'xx_efx'),
(n:827;name:'xx_efx'),
(n:828;name:'xx_efx'),
(n:829;name:'xx_efx'),
(n:830;name:'xx_snow_stuff'),
(n:830;name:'xx_snowtree'),
(n:834;name:'xx_mecc_base'),
(n:834;name:'xx_smartie_stuff'),
(n:835;name:'xx_smartie_stuff'),
(n:836;name:'xx_smartie_stuff'),
(n:837;name:'xx_efx'),
(n:839;name:'xx_efx'),
(n:840;name:'xx_efx'),
(n:841;name:'xx_efx'),
(n:846;name:'xx_efx'),
(n:847;name:'xx_efx'),
(n:848;name:'xx_efx'),
(n:849;name:'xx_efx'),
(n:850;name:'xx_efx'),
(n:851;name:'xx_reaper_base'),
(n:854;name:'xx_efx'),
(n:857;name:'xx_reaper_base'),
(n:858;name:'xx_reaper_base'),
(n:859;name:'xx_efx'),
(n:861;name:'xx_efx'),
(n:862;name:'xx_efx'),
(n:866;name:'xx_efx'),
(n:867;name:'xx_efx'),
(n:868;name:'xx_efx'),
(n:869;name:'xx_efx'),
(n:872;name:'xx_efx'),
(n:873;name:'xx_efx'),
(n:874;name:'xx_efx'),
(n:875;name:'xx_efx'),
(n:882;name:'xx_reaper_base'),
(n:883;name:'xx_efx'),
(n:884;name:'xx_efx'),
(n:885;name:'xx_efx'),
(n:886;name:'xx_efx'),
(n:887;name:'xx_efx'),
(n:888;name:'xx_efx'),
(n:890;name:'xx_efx'),
(n:892;name:'xx_mecclev1'),
(n:892;name:'xx_rpman_weapons'),
(n:894;name:'xx_efx'),
(n:897;name:'xx_mecclev1'),
(n:897;name:'xx_rpman_weapons'),
(n:898;name:'xx_mecclev1'),
(n:898;name:'xx_rpman_weapons'),
(n:899;name:'xx_efx'),
(n:900;name:'xx_efx'),
(n:901;name:'xx_efx'),
(n:902;name:'xx_mecclev1'),
(n:902;name:'xx_rpman_weapons'),
(n:903;name:'xx_reaperlev1'),
(n:904;name:'xx_efx'),
(n:905;name:'xx_efx'),
(n:906;name:'xx_efx'),
(n:907;name:'xx_efx'),
(n:908;name:'xx_efx'),
(n:909;name:'xx_efx'),
(n:910;name:'xx_efx'),
(n:911;name:'xx_efx'),
(n:912;name:'xx_efx'),
(n:913;name:'xx_efx'),
(n:914;name:'xx_efx'),
(n:915;name:'xx_efx'),
(n:916;name:'xx_efx'),
(n:917;name:'xx_efx'),
(n:918;name:'xx_mecc_base'),
(n:919;name:'xx_efx'),
(n:920;name:'xx_mecclev1'),
(n:920;name:'xx_rpman_weapons'),
(n:921;name:'xx_efx'),
(n:922;name:'xx_efx'),
(n:923;name:'xx_efx'),
(n:924;name:'xx_efx'),
(n:925;name:'xx_efx'),
(n:926;name:'xx_efx'),
(n:927;name:'xx_efx'),
(n:928;name:'xx_reaperlev1'),
(n:929;name:'xx_reaperlev1'),
(n:930;name:'xx_reaperlev1'),
(n:931;name:'xx_reaperlev1'),
(n:932;name:'xx_efx'),
(n:933;name:'xx_efx'),
(n:934;name:'xx_reaperlev1'),
(n:935;name:'xx_efx'),
(n:936;name:'xx_mecc_base'),
(n:937;name:'xx_tools'),
(n:938;name:'xx_efx'),
(n:942;name:'xx_efx'),
(n:945;name:'xx_offspring'),
(n:946;name:'xx_efx'),
(n:947;name:'xx_efx'),
(n:948;name:'xx_efx'),
(n:950;name:'xx_efx'),
(n:951;name:'xx_smartie_stuff'),
(n:952;name:'xx_smartie_stuff'),
(n:953;name:'xx_smartie_stuff'),
(n:954;name:'xx_smartie_stuff'),
(n:955;name:'xx_efx'),
(n:956;name:'xx_efx'),
(n:959;name:'xx_efx'),
(n:960;name:'xx_efx'),
(n:964;name:'xx_efx'),
(n:965;name:'xx_efx'),
(n:966;name:'xx_efx'),
(n:967;name:'xx_reaper_base'),
(n:968;name:'xx_reaper_base'),
(n:970;name:'xx_reaper_base'),
(n:977;name:'xx_bones'),
(n:978;name:'xx_bones'),
(n:979;name:'xx_bones'),
(n:980;name:'xx_efx'),
(n:981;name:'xx_mecc_base'),
(n:983;name:'xx_mecc_base'),
(n:984;name:'xx_mecc_base'),
(n:985;name:'xx_reaper_base'),
(n:986;name:'xx_mecc_base'),
(n:988;name:'xx_mecc_base'),
(n:989;name:'xx_reaper_base'),
(n:991;name:'xx_mecc_base'),
(n:992;name:'xx_plants'),
(n:993;name:'xx_plants'),
(n:994;name:'xx_plants'),
(n:996;name:'xx_plants'),
(n:997;name:'xx_plants'),
(n:998;name:'xx_plants'),
(n:999;name:'xx_plants'),
(n:1001;name:'xx_story1'),
(n:1002;name:'xx_smartie_stuff'),
(n:1003;name:'xx_smartie_stuff'),
(n:1004;name:'xx_tools'),
(n:1005;name:'xx_permanentaliens'),
(n:1006;name:'xx_ptree'),
(n:1007;name:'xx_bigwalls'),
(n:1007;name:'xx_bigwalls_lite'),
(n:1008;name:'xx_story1'),
(n:1009;name:'xx_story1'),
(n:1009;name:'xx_story1'),
(n:1009;name:'xx_story1'),
(n:1009;name:'xx_story1'),
(n:1010;name:'xx_story1'),
(n:1011;name:'xx_story1'),
(n:1012;name:'xx_story1'),
(n:1013;name:'xx_story1'),
(n:1014;name:'xx_story1'),
(n:1015;name:'xx_bigwalls'),
(n:1016;name:'xx_efx'),
(n:1017;name:'xx_tools'),
(n:1018;name:'xx_kabutolev1'),
(n:1019;name:'xx_menus'),
(n:1020;name:'xx_menus'),
(n:1021;name:'xx_guard_drawbridge'),
(n:1022;name:'xx_bigwalls'),
(n:1023;name:'xx_guard_prison'),
(n:1024;name:'xx_smartie_stuff'),
(n:1025;name:'xx_menus'),
(n:1026;name:'xx_menus'),
(n:1027;name:'xx_menus'),
(n:1028;name:'xx_smartie_stuff'),
(n:1029;name:'xx_plants'),
(n:1030;name:'xx_plants'),
(n:1031;name:'xx_plants'),
(n:1041;name:'xx_smartie_stuff'),
(n:1042;name:'xx_rocks'),
(n:1043;name:'xx_rocks'),
(n:1044;name:'xx_rocks'),
(n:1045;name:'xx_ptree'),
(n:1047;name:'xx_reaperman'),
(n:1048;name:'xx_reaperman'),
(n:1049;name:'xx_reaperman'),
(n:1050;name:'xx_guard_buildings'),
(n:1051;name:'xx_guard_buildings'),
(n:1052;name:'xx_markers'),
(n:1053;name:'xx_story4'),
(n:1054;name:'xx_formations'),
(n:1055;name:'xx_reaperman'),
(n:1056;name:'xx_guard_drawbridge'),
(n:1057;name:'xx_story4'),
(n:1058;name:'xx_formations'),
(n:1059;name:'xx_formations'),
(n:1060;name:'xx_guard_barracks'),
(n:1061;name:'xx_guard_buildings'),
(n:1061;name:'xx_guard_turrets'),
(n:1062;name:'xx_guard_buildings'),
(n:1062;name:'xx_guard_turrets'),
(n:1063;name:'xx_guard_prison'),
(n:1064;name:'xx_charger'),
(n:1065;name:'xx_guard_buildings'),
(n:1066;name:'xx_guard_buildings'),
(n:1067;name:'xx_formations'),
(n:1068;name:'xx_formations'),
(n:1069;name:'xx_formations'),
(n:1070;name:'xx_formations'),
(n:1071;name:'xx_formations'),
(n:1072;name:'xx_guard_buildings'),
(n:1073;name:'xx_smartie_stuff'),
(n:1074;name:'xx_guard_buildings'),
(n:1075;name:'xx_smartie_stuff'),
(n:1076;name:'xx_jetski'),
(n:1077;name:'xx_guard_reaper_tower'),
(n:1078;name:'xx_smartie_stuff'),
(n:1079;name:'xx_reaperman'),
(n:1080;name:'xx_raik'),
(n:1081;name:'xx_snow_stuff'),
(n:1082;name:'xx_smyan_pagoda'),
(n:1083;name:'xx_smyan_pagoda'),
(n:1084;name:'xx_smartie_stuff'),
(n:1084;name:'xx_smyan_pagoda'),
(n:1085;name:'xx_snow_stuff'),
(n:1086;name:'xx_snow_stuff'),
(n:1087;name:'xx_snow_stuff'),
(n:1088;name:'xx_snow_stuff'),
(n:1089;name:'xx_snow_stuff'),
(n:1092;name:'xx_guard_buildings'),
(n:1093;name:'xx_mecc_base'),
(n:1094;name:'xx_guard_buildings'),
(n:1095;name:'xx_mecc_base'),
(n:1096;name:'xx_rocks'),
(n:1097;name:'xx_guard_buildings'),
(n:1098;name:'xx_markers'),
(n:1099;name:'xx_jetski'),
(n:1100;name:'xx_jetski'),
(n:1101;name:'xx_jetski'),
(n:1102;name:'xx_efx'),
(n:1104;name:'xx_ripper'),
(n:1105;name:'xx_ripper'),
(n:1106;name:'xx_efx'),
(n:1107;name:'xx_efx'),
(n:1108;name:'xx_efx'),
(n:1109;name:'xx_efx'),
(n:1111;name:'xx_efx'),
(n:1112;name:'xx_efx'),
(n:1113;name:'xx_efx'),
(n:1114;name:'xx_mecc_flick'),
(n:1114;name:'xx_mecclev1'),
(n:1114;name:'xx_rpman_weapons'),
(n:1115;name:'xx_formations'),
(n:1116;name:'xx_sonak'),
(n:1117;name:'xx_vimp'),
(n:1118;name:'xx_vimp'),
(n:1119;name:'xx_vimp'),
(n:1120;name:'xx_efx'),
(n:1121;name:'xx_efx'),
(n:1122;name:'xx_efx'),
(n:1123;name:'xx_mecclev1'),
(n:1123;name:'xx_rpman_weapons'),
(n:1124;name:'xx_efx'),
(n:1125;name:'xx_efx'),
(n:1126;name:'xx_giants_logo_3d'),
(n:1127;name:'xx_guard_buildings'),
(n:1128;name:'xx_guard_buildings'),
(n:1129;name:'xx_guard_buildings'),
(n:1130;name:'xx_efx'),
(n:1134;name:'xx_efx'),
(n:1135;name:'xx_efx'),
(n:1136;name:'xx_efx'),
(n:1137;name:'xx_efx'),
(n:1138;name:'xx_guard_buildings'),
(n:1139;name:'xx_efx'),
(n:1140;name:'xx_efx'),
(n:1142;name:'xx_efx'),
(n:1144;name:'xx_ptree'),
(n:1145;name:'xx_efx'),
(n:1146;name:'xx_rstory4'),
(n:1147;name:'xx_rstory3'),
(n:1147;name:'xx_rstory5'),
(n:1148;name:'xx_reaper_base'),
(n:1149;name:'xx_reaper_base'),
(n:1150;name:'xx_reaper_base'),
(n:1151;name:'xx_reaper_base'),
(n:1152;name:'xx_reaper_base'),
(n:1153;name:'xx_reaper_base'),
(n:1154;name:'xx_reaper_base'),
(n:1155;name:'xx_reaper_base'),
(n:1156;name:'xx_reaper_base'),
(n:1157;name:'xx_reaper_base'),
(n:1158;name:'xx_reaper_base'),
(n:1159;name:'xx_jetski_rpm'),
(n:1160;name:'xx_rstory3'),
(n:1160;name:'xx_rstory5'),
(n:1161;name:'xx_guard_army_barracks'),
(n:1162;name:'xx_markers'),
(n:1163;name:'xx_rocks'),
(n:1164;name:'xx_rstory3'),
(n:1164;name:'xx_rstory5'),
(n:1165;name:'xx_efx'),
(n:1166;name:'xx_rstory5'),
(n:1168;name:'xx_toby'),
(n:1169;name:'xx_story4'),
(n:1170;name:'xx_efx'),
(n:1171;name:'xx_reaper_ship'),
(n:1172;name:'xx_reaper_ship'),
(n:1173;name:'xx_guard_army_barracks'),
(n:1174;name:'xx_formations'),
(n:1175;name:'xx_kab_stuff'),
(n:1176;name:'xx_formations'),
(n:1177;name:'xx_formations'),
(n:1178;name:'xx_formations'),
(n:1180;name:'xx_formations'),
(n:1181;name:'xx_reaper_base'),
(n:1185;name:'xx_mecc_base'),
(n:1186;name:'xx_mecc_base'),
(n:1187;name:'xx_reaper_base'),
(n:1188;name:'xx_reaper_base'),
(n:1189;name:'xx_reaper_base'),
(n:1190;name:'xx_guard_barracks'),
(n:1192;name:'xx_reaper_base'),
(n:1198;name:'xx_lander'),
(n:1199;name:'xx_kab_stuff'),
(n:1200;name:'xx_smyan'),
(n:1200;name:'xx_smyan_flick'),
(n:1201;name:'xx_story4'),
(n:1202;name:'xx_story4'),
(n:1203;name:'xx_reaperman'),
(n:1204;name:'xx_kab_stuff'),
(n:1204;name:'xx_kabuto_flick'),
(n:1205;name:'xx_efx'),
(n:1206;name:'xx_efx'),
(n:1207;name:'xx_giantwalls'),
(n:1208;name:'xx_giantwalls'),
(n:1209;name:'xx_giantwalls'),
(n:1210;name:'xx_kab_stuff'),
(n:1211;name:'xx_guard_buildings'),
(n:1212;name:'xx_smtimmy'),
(n:1212;name:'xx_smtimmy_flick'),
(n:1213;name:'xx_guard_buildings'),
(n:1214;name:'xx_reaper_ship'),
(n:1215;name:'xx_kab_stuff'),
(n:1216;name:'xx_kstory5'),
(n:1217;name:'xx_smdoomed'),
(n:1218;name:'xx_smdoomed'),
(n:1219;name:'xx_formations'),
(n:1220;name:'xx_formations'),
(n:1221;name:'xx_efx'),
(n:1222;name:'xx_reaperlev1'),
(n:1223;name:'xx_reaperlev1'),
(n:1224;name:'xx_reaperlev1'),
(n:1225;name:'xx_reaperlev1'),
(n:1226;name:'xx_guard_barracks'),
(n:1228;name:'xx_reaper_base'),
(n:1229;name:'xx_reaper_base'),
(n:1230;name:'xx_reaper_base'),
(n:1231;name:'xx_reaper_base'),
(n:1233;name:'xx_reaperlev1'),
(n:1234;name:'xx_story1'),
(n:1235;name:'xx_story1'),
(n:1236;name:'xx_story1'),
(n:1237;name:'xx_mecc_base'),
(n:1238;name:'xx_reaper_base'),
(n:1239;name:'xx_raik'),
(n:1240;name:'xx_rpqueen'),
(n:1241;name:'xx_theend'),
(n:1242;name:'xx_kab_stuff'),
(n:1242;name:'xx_seamonster'),
(n:1243;name:'xx_kab_stuff'),
(n:1244;name:'xx_kab_stuff'),
(n:1245;name:'xx_efx'),
(n:1246;name:'xx_kab_stuff'),
(n:1247;name:'xx_story1'),
(n:1248;name:'xx_story1'),
(n:1249;name:'xx_story1'),
(n:1250;name:'xx_story1'),
(n:1251;name:'xx_story1'),
(n:1252;name:'xx_story1'),
(n:1253;name:'xx_story1'),
(n:1255;name:'xx_reaper_base'),
(n:1256;name:'xx_efx'),
(n:1257;name:'xx_efx'),
(n:1258;name:'xx_efx'),
(n:1259;name:'xx_story1'),
(n:1274;name:'xx_plants'),
(n:1275;name:'xx_tools'),
(n:1276;name:'xx_guard_barracks'),
(n:1277;name:'xx_giantwalls'),
(n:1279;name:'xx_ambient'),
(n:1280;name:'xx_ambient'),
(n:1281;name:'xx_ambient'),
(n:1282;name:'xx_ambient'),
(n:1283;name:'xx_ambient'),
(n:1284;name:'xx_ambient'),
(n:1285;name:'xx_ambient'),
(n:1286;name:'xx_ambient'),
(n:1287;name:'xx_ambient'),
(n:1288;name:'xx_ambient'),
(n:1289;name:'xx_ambient'),
(n:1290;name:'xx_ambient'),
(n:1291;name:'xx_ambient'),
(n:1293;name:'xx_ambient'),
(n:1295;name:'xx_ambient'),
(n:1296;name:'xx_ambient'),
(n:1297;name:'xx_ambient'),
(n:1298;name:'xx_ambient'),
(n:1299;name:'xx_ambient'),
(n:1300;name:'xx_ambient'),
(n:1301;name:'xx_ambient'),
(n:1302;name:'xx_ambient'),
(n:1303;name:'xx_ambient'),
(n:1304;name:'xx_ambient'),
(n:1305;name:'xx_ambient'),
(n:1306;name:'xx_ambient'),
(n:1308;name:'xx_ambient'),
(n:1309;name:'xx_ambient'),
(n:1310;name:'xx_ambient'),
(n:1312;name:'xx_ambient'),
(n:1313;name:'xx_ambient'),
(n:1314;name:'xx_formations'),
(n:1315;name:'xx_ambient'),
(n:1316;name:'xx_ambient'),
(n:1317;name:'xx_ambient'),
(n:1318;name:'xx_ambient'),
(n:1319;name:'xx_ambient'),
(n:1320;name:'xx_ambient'),
(n:1322;name:'xx_efx'),
(n:1323;name:'xx_music_temp'),
(n:1324;name:'xx_music_temp'),
(n:1325;name:'xx_music_temp'),
(n:1326;name:'xx_music_temp'),
(n:1327;name:'xx_music_temp'),
(n:1328;name:'xx_story4'),
(n:1330;name:'xx_guard_buildings'),
(n:1331;name:'xx_jetski_rpm'),
(n:1332;name:'xx_reaper_base'),
(n:1333;name:'xx_giantwalls'),
(n:1334;name:'xx_kab_stuff'),
(n:1335;name:'xx_smartie_stuff'),
(n:1336;name:'xx_smartie_stuff'),
(n:1337;name:'xx_sm_evil'),
(n:1338;name:'xx_ambient'),
(n:1339;name:'xx_ambient'),
(n:1340;name:'xx_ambient'),
(n:1342;name:'xx_ambient'),
(n:1343;name:'xx_ambient'),
(n:1344;name:'xx_ambient'),
(n:1348;name:'xx_smartie_stuff'),
(n:1349;name:'xx_jetski'),
(n:1350;name:'xx_reaper_base'),
(n:1351;name:'xx_reaper_base'),
(n:1354;name:'xx_smartie_stuff'),
(n:1355;name:'xx_ambient'),
(n:1356;name:'xx_rstory5'),
(n:1357;name:'xx_rstory5'),
(n:1358;name:'xx_efx'),
(n:1359;name:'xx_giantwalls'),
(n:1360;name:'xx_efx'),
(n:1361;name:'xx_efx'),
(n:1363;name:'xx_efx'),
(n:1364;name:'xx_efx'),
(n:1365;name:'xx_efx'),
(n:1366;name:'xx_efx'),
(n:1367;name:'xx_efx'),
(n:1368;name:'xx_efx'),
(n:1369;name:'xx_efx'),
(n:1370;name:'xx_kstory5'),
(n:1371;name:'xx_kstory5'),
(n:1372;name:'xx_kstory5'),
(n:1373;name:'xx_kstory5'),
(n:1374;name:'xx_jetski'),
(n:1375;name:'xx_kab_stuff'),
(n:1376;name:'xx_guard_barracks'),
(n:1377;name:'xx_guard_barracks'),
(n:1378;name:'xx_guard_barracks'),
(n:1379;name:'xx_guard_barracks'),
(n:1380;name:'xx_guard_barracks'),
(n:1381;name:'xx_guard_buildings'),
(n:1382;name:'xx_guard_buildings'),
(n:1383;name:'xx_guard_buildings'),
(n:1384;name:'xx_guard_buildings'),
(n:1385;name:'xx_guard_buildings'),
(n:1386;name:'xx_guard_buildings'),
(n:1387;name:'xx_guard_buildings'),
(n:1388;name:'xx_guard_buildings'),
(n:1389;name:'xx_guard_buildings'),
(n:1390;name:'xx_guard_buildings'),
(n:1391;name:'xx_guard_barracks'),
(n:1392;name:'xx_guard_barracks'),
(n:1393;name:'xx_guard_barracks'),
(n:1394;name:'xx_giantwalls'),
(n:1395;name:'xx_giantwalls'),
(n:1396;name:'xx_giantwalls'),
(n:1397;name:'xx_giantwalls'),
(n:1398;name:'xx_giantwalls'),
(n:1399;name:'xx_giantwalls'),
(n:1400;name:'xx_giantwalls'),
(n:1401;name:'xx_giantwalls'),
(n:1402;name:'xx_giantwalls'),
(n:1403;name:'xx_giantwalls'),
(n:1404;name:'xx_giantwalls'),
(n:1405;name:'xx_giantwalls'),
(n:1406;name:'xx_giantwalls'),
(n:1407;name:'xx_giantwalls'),
(n:1408;name:'xx_giantwalls'),
(n:1409;name:'xx_giantwalls'),
(n:1410;name:'xx_giantwalls'),
(n:1411;name:'xx_giantwalls'),
(n:1412;name:'xx_efx'),
(n:1413;name:'xx_bridge'),
(n:1414;name:'xx_guard_drawbridge'),
(n:1415;name:'xx_guard_drawbridge'),
(n:1416;name:'xx_kab_stuff'),
(n:1417;name:'xx_efx'));}
prefer:array[0..13] of string=(
'xx_kabutolev1',
'xx_mecclev1',
'xx_reaperlev1',
'xx_seamonster',
'xx_bigwalls_lite',
'xx_smtimmy',
'xx_mecc_base',
'xx_reaper_base',
'xx_rpqueen',
'xx_smartie_stuff',
'xx_snow_stuff',
'xx_guard_turrets',
'xx_rstory5',
'xx_kab_stuff');


implementation

end.
